-- DoctrineData.lua
-- Auto-generated Content Registry: Doctrines (32 entries)
-- Do not edit manually. Regenerate from CTRBLXAI.db.

local DoctrineData = {
	["DOC-VANGUARD"] = {
		name = "Vanguard",
		identity = "Frontline durability",
		statPackage = {STR = 5, AGI = -10, INT = -10, VIT = 15, DEX = 5, LUK = -5},
		passiveName = "Bulwark",
		passiveActivation = "At least one standing ally within Range 2",
		passiveEffect = "Direct final damage received -10%; Stability +1",
		passiveRangePattern = "Range 2",
		passiveDuration = "Passive",
		passiveFrequency = "Continuous while condition true",
		passiveStacking = "Additional allies do not stack",
		breakBehavior = "Disabled by Break; pre-existing snapshot effects persist only where explicitly stated",
		skillChoices = {"DOC-VANGUARD-01", "SKL-WEAPON-WARD", "SKL-BASTION-PROJECTION"},
		activeChoiceCount = 1,
		augmentSlotRule = "Every Doctrine Skill has exactly 2 Augment Slots",
		associatedSkillFamily = "Vanguard",
		scarcity = "One scarcity band comparable to Epic-to-Legendary equipment",
	},
	["DOC-BERSERKER"] = {
		name = "Berserker",
		identity = "Risk and reward melee",
		statPackage = {STR = 15, AGI = 5, INT = -15, VIT = 5, DEX = -5, LUK = -5},
		passiveName = "Blood Frenzy",
		passiveActivation = "Current HP below 50% Max HP",
		passiveEffect = "Final damage dealt +20%; direct final damage received +10%",
		passiveRangePattern = "Self",
		passiveDuration = "Passive",
		passiveFrequency = "Continuous while condition true",
		passiveStacking = "Does not stack",
		breakBehavior = "Disabled by Break; pre-existing snapshot effects persist only where explicitly stated",
		skillChoices = {"DOC-BERSERKER-01", "SKL-POWER-STRIKE", "SKL-EXECUTION-STROKE"},
		activeChoiceCount = 1,
		augmentSlotRule = "Every Doctrine Skill has exactly 2 Augment Slots",
		associatedSkillFamily = "Berserker",
		scarcity = "One scarcity band comparable to Epic-to-Legendary equipment",
	},
	["DOC-ARCANIST"] = {
		name = "Arcanist",
		identity = "Resource-intensive Skill use",
		statPackage = {STR = -10, AGI = -5, INT = 15, VIT = -10, DEX = 5, LUK = 5},
		passiveName = "Arcane Efficiency",
		passiveActivation = "First Skill committed each unit turn",
		passiveEffect = "Final ordinary MP Cost -25%; minimum positive ordinary cost 1; external added MP unaffected",
		passiveRangePattern = "Self",
		passiveDuration = "One Skill commitment",
		passiveFrequency = "Once per unit turn",
		breakBehavior = "Disabled by Break; pre-existing snapshot effects persist only where explicitly stated",
		skillChoices = {"DOC-ARCANIST-01", "SKL-FIRE-BOLT", "SKL-METEOR-MARKER"},
		activeChoiceCount = 1,
		augmentSlotRule = "Every Doctrine Skill has exactly 2 Augment Slots",
		associatedSkillFamily = "Arcanist",
		scarcity = "One scarcity band comparable to Epic-to-Legendary equipment",
	},
	["DOC-TACTICIAN"] = {
		name = "Tactician",
		identity = "Timeline and battlefield control",
		statPackage = {STR = -5, AGI = -5, INT = 5, VIT = -15, DEX = 10, LUK = 10},
		passiveName = "Command Tempo",
		passiveActivation = "Standing allies in range",
		passiveEffect = "Skill RT Cost -10%; excludes Channel, Activation, Move, Basic Attack, Guard, Item, Interact",
		passiveRangePattern = "Aura Range 3",
		passiveDuration = "Passive",
		passiveFrequency = "Continuous",
		passiveStacking = "Multiple sources use strongest",
		breakBehavior = "Disabled by Break; pre-existing snapshot effects persist only where explicitly stated",
		skillChoices = {"DOC-TACTICIAN-01", "SKL-PHANTOM-EXCHANGE", "SKL-RAINFALL-ZONE"},
		activeChoiceCount = 1,
		augmentSlotRule = "Every Doctrine Skill has exactly 2 Augment Slots",
		associatedSkillFamily = "Tactician",
		scarcity = "One scarcity band comparable to Epic-to-Legendary equipment",
	},
	["DOC-RANGER"] = {
		name = "Ranger",
		identity = "Positioning and ranged precision",
		statPackage = {STR = -5, AGI = 10, INT = -10, VIT = -15, DEX = 15, LUK = 5},
		passiveName = "Steady Aim",
		passiveActivation = "Ranger has not used Move this unit turn",
		passiveEffect = "Direct attacks/Direct Damage Skills gain Hit Quality +0.15; projectile Maximum Range +1; Minimum Range unchanged",
		passiveRangePattern = "Self",
		passiveDuration = "Current unit turn",
		passiveFrequency = "Continuous while condition true",
		passiveStacking = "Move removes for rest of turn",
		breakBehavior = "Disabled by Break; pre-existing snapshot effects persist only where explicitly stated",
		skillChoices = {"DOC-RANGER-01", "SKL-LONGSHOT", "SKL-HAMSTRING"},
		activeChoiceCount = 1,
		augmentSlotRule = "Every Doctrine Skill has exactly 2 Augment Slots",
		associatedSkillFamily = "Ranger",
		scarcity = "One scarcity band comparable to Epic-to-Legendary equipment",
	},
	["DOC-WARLORD"] = {
		name = "Warlord",
		identity = "Offensive party support",
		statPackage = {STR = 10, AGI = -5, INT = -10, VIT = 10, DEX = -10, LUK = 5},
		passiveName = "Commanding Presence",
		passiveActivation = "Standing allies in range",
		passiveEffect = "Affected allies deal +10% direct final damage; Warlord requires another source to benefit",
		passiveRangePattern = "Aura Range 3",
		passiveDuration = "Passive",
		passiveFrequency = "Continuous",
		passiveStacking = "Multiple sources use strongest",
		breakBehavior = "Disabled by Break; pre-existing snapshot effects persist only where explicitly stated",
		skillChoices = {"DOC-WARLORD-01", "SKL-GUARDIAN-S-PROJECTION", "SKL-CRUSHING-ADVANCE"},
		activeChoiceCount = 1,
		augmentSlotRule = "Every Doctrine Skill has exactly 2 Augment Slots",
		associatedSkillFamily = "Warlord",
		scarcity = "One scarcity band comparable to Epic-to-Legendary equipment",
	},
	["DOC-SHADOWBINDER"] = {
		name = "Shadowbinder",
		identity = "Debuff specialization",
		statPackage = {STR = -10, AGI = -5, INT = 10, VIT = -15, DEX = 5, LUK = 15},
		passiveName = "Malignancy",
		passiveActivation = "Unit applies eligible debuff",
		passiveEffect = "Authored duration +20% before Debuff Resistance and boss modifiers; excludes Permanent, Unlimited, instant",
		passiveRangePattern = "Source-owned debuff",
		passiveDuration = "Per debuff application",
		passiveFrequency = "Per eligible application",
		breakBehavior = "Disabled by Break; pre-existing snapshot effects persist only where explicitly stated",
		skillChoices = {"DOC-SHADOWBINDER-01", "SKL-STONE-PRISON", "SKL-FROSTBIND"},
		activeChoiceCount = 1,
		augmentSlotRule = "Every Doctrine Skill has exactly 2 Augment Slots",
		associatedSkillFamily = "Shadowbinder",
		scarcity = "One scarcity band comparable to Epic-to-Legendary equipment",
	},
	["DOC-SPELLBLADE"] = {
		name = "Spellblade",
		identity = "Hybrid weapon and Skill use",
		statPackage = {STR = 10, AGI = -5, INT = 10, VIT = -10, DEX = 5, LUK = -10},
		passiveName = "Arcane Edge",
		passiveActivation = "Physical Direct Damage Skill with positive Weapon Attack Power scaling committed",
		passiveEffect = "Skill Potency Multiplier +10% for that resolution; not Basic Attack",
		passiveRangePattern = "Self",
		passiveDuration = "Skill resolution",
		passiveFrequency = "Per eligible Skill",
		passiveStacking = "Validated at commitment",
		breakBehavior = "Disabled by Break; pre-existing snapshot effects persist only where explicitly stated",
		skillChoices = {"DOC-SPELLBLADE-01", "SKL-POWER-STRIKE", "SKL-LUCKY-STRIKE"},
		activeChoiceCount = 1,
		augmentSlotRule = "Every Doctrine Skill has exactly 2 Augment Slots",
		associatedSkillFamily = "Spellblade",
		scarcity = "One scarcity band comparable to Epic-to-Legendary equipment",
	},
	["DOC-ASCETIC"] = {
		name = "Ascetic",
		identity = "Sustain and resource recovery",
		statPackage = {STR = -10, AGI = -5, INT = 10, VIT = 10, DEX = 5, LUK = -10},
		passiveName = "Inner Reserve",
		passiveActivation = "First completed active Skill each unit turn that spends MP",
		passiveEffect = "Restore 5% Max MP after full resolution; excludes zero-MP, passive, reaction, item, external MP loss",
		passiveRangePattern = "Self",
		passiveDuration = "Unit turn",
		passiveFrequency = "Once per unit turn",
		breakBehavior = "Disabled by Break; pre-existing snapshot effects persist only where explicitly stated",
		skillChoices = {"DOC-ASCETIC-01", "SKL-HEALING-LIGHT", "SKL-PURIFYING-FORM"},
		activeChoiceCount = 1,
		augmentSlotRule = "Every Doctrine Skill has exactly 2 Augment Slots",
		associatedSkillFamily = "Ascetic",
		scarcity = "One scarcity band comparable to Epic-to-Legendary equipment",
	},
	["DOC-TRICKSTER"] = {
		name = "Trickster",
		identity = "Fortune and positioning",
		statPackage = {STR = -10, AGI = 10, INT = -5, VIT = -15, DEX = 5, LUK = 15},
		passiveName = "Fleeting Step",
		passiveActivation = "First Utility Skill committed each unit turn",
		passiveEffect = "Skill RT Cost -25%; Channel/Activation unchanged; minimum 0",
		passiveRangePattern = "Self",
		passiveDuration = "Unit turn",
		passiveFrequency = "Once per unit turn",
		breakBehavior = "Disabled by Break; pre-existing snapshot effects persist only where explicitly stated",
		skillChoices = {"DOC-TRICKSTER-01", "SKL-BLINK", "SKL-FATED-ESCAPE"},
		activeChoiceCount = 1,
		augmentSlotRule = "Every Doctrine Skill has exactly 2 Augment Slots",
		associatedSkillFamily = "Trickster",
		scarcity = "One scarcity band comparable to Epic-to-Legendary equipment",
	},
	["DOC-THIEF"] = {
		name = "Thief",
		identity = "Loot acquisition and Fortune",
		statPackage = {STR = -10, AGI = 10, INT = -10, VIT = -10, DEX = 10, LUK = 10},
		passiveName = "Fortune Hand",
		passiveActivation = "Eligible Thief Skill directly generates/determines reward opportunity",
		passiveEffect = "Add 50% of Thief Unit Fortune to effective Expedition Fortune for that reward only; no slots/category unlocks",
		passiveRangePattern = "Eligible reward",
		passiveDuration = "Per eligible reward opportunity",
		passiveFrequency = "As Skill generates",
		passiveStacking = "Does not affect unrelated KO rewards",
		breakBehavior = "Disabled by Break; pre-existing snapshot effects persist only where explicitly stated",
		skillChoices = {"SKL-STEAL", "DOC-THIEF-01", "SKL-OPPORTUNIST-S-STEP"},
		activeChoiceCount = 1,
		augmentSlotRule = "Every Doctrine Skill has exactly 2 Augment Slots",
		associatedSkillFamily = "Thief",
		scarcity = "One scarcity band comparable to Epic-to-Legendary equipment",
	},
	["DOC-DUELIST"] = {
		name = "Duelist",
		identity = "Single-weapon mastery",
		statPackage = {STR = 5, AGI = 10, INT = -10, VIT = -10, DEX = 10, LUK = -5},
		passiveName = "Single-Weapon Mastery",
		passiveActivation = "Naturally legal 1H main hand; empty off-hand; no Colossal Arsenal",
		passiveEffect = "Basic Attack final damage +20%; RT -15%; Hit Quality +0.15; Evasiveness +10%; delivered Weapon RT Delay +15%",
		passiveRangePattern = "Self",
		passiveDuration = "Passive",
		passiveFrequency = "Continuous while equipment valid",
		breakBehavior = "Disabled by Break; pre-existing snapshot effects persist only where explicitly stated",
		skillChoices = {"DOC-DUELIST-01", "SKL-PRECISE-DISARM", "SKL-LUCKY-STRIKE"},
		activeChoiceCount = 1,
		augmentSlotRule = "Every Doctrine Skill has exactly 2 Augment Slots",
		associatedSkillFamily = "Duelist",
		scarcity = "One scarcity band comparable to Epic-to-Legendary equipment",
	},
	["DOC-TWINBLADE"] = {
		name = "Twinblade",
		identity = "Dual-wield combat",
		statPackage = {STR = 10, AGI = 10, INT = -10, VIT = -10, DEX = 5, LUK = -5},
		passiveName = "Dual-Wield Discipline",
		passiveActivation = "Two naturally legal 1H weapons equipped",
		passiveEffect = "Permits ordinary dual wield at 75% numerical properties; locked dual-wield RT, Knockback, delivery and Skill rules apply",
		passiveRangePattern = "Equipment state",
		passiveDuration = "Passive",
		passiveFrequency = "Continuous",
		passiveStacking = "Break inactivates off hand without unequipping",
		breakBehavior = "Disabled by Break; pre-existing snapshot effects persist only where explicitly stated",
		skillChoices = {"DOC-TWINBLADE-01", "SKL-RAPID-ASSAULT", "DOC-TWINBLADE-02"},
		activeChoiceCount = 1,
		augmentSlotRule = "Every Doctrine Skill has exactly 2 Augment Slots",
		associatedSkillFamily = "Twinblade",
		scarcity = "One scarcity band comparable to Epic-to-Legendary equipment",
	},
	["DOC-JUGGERNAUT"] = {
		name = "Juggernaut",
		identity = "Heavy melee pressure",
		statPackage = {STR = 15, AGI = -10, INT = -10, VIT = 10, LUK = -5},
		passiveName = "Two-Handed Mastery",
		passiveActivation = "Naturally legal 2H melee main-hand weapon at 100% normal use",
		passiveEffect = "Basic Attack final damage +15%; Direct Damage Skill final damage +15%; delivered Weapon RT Delay +15%; excludes Colossal conversion",
		passiveRangePattern = "Self",
		passiveDuration = "Passive",
		passiveFrequency = "Continuous while equipment valid",
		breakBehavior = "Disabled by Break; pre-existing snapshot effects persist only where explicitly stated",
		skillChoices = {"DOC-JUGGERNAUT-01", "SKL-SWEEPING-CUT", "SKL-CRUSHING-ADVANCE"},
		activeChoiceCount = 1,
		augmentSlotRule = "Every Doctrine Skill has exactly 2 Augment Slots",
		associatedSkillFamily = "Juggernaut",
		scarcity = "One scarcity band comparable to Epic-to-Legendary equipment",
	},
	["DOC-CONJURER"] = {
		name = "Conjurer",
		identity = "Summoning",
		statPackage = {STR = -10, AGI = -10, INT = 15, VIT = 5, DEX = 5, LUK = -5},
		passiveName = "Bound Host",
		passiveActivation = "Summon created while passive active",
		passiveEffect = "Summon Max HP +10%, final damage +10%, healing +10%; snapshot at creation",
		passiveRangePattern = "Owned summons",
		passiveDuration = "Summon lifetime",
		passiveFrequency = "At summon creation",
		passiveStacking = "Existing summons retain snapshot after Break",
		breakBehavior = "Disabled by Break; pre-existing snapshot effects persist only where explicitly stated",
		skillChoices = {"DOC-CONJURER-01", "DOC-CONJURER-02", "DOC-CONJURER-03"},
		activeChoiceCount = 1,
		augmentSlotRule = "Every Doctrine Skill has exactly 2 Augment Slots",
		associatedSkillFamily = "Conjurer",
		scarcity = "One scarcity band comparable to Epic-to-Legendary equipment",
	},
	["DOC-CLERIC"] = {
		name = "Cleric",
		identity = "Dedicated healing and ally preservation",
		statPackage = {STR = -10, AGI = -5, INT = 15, VIT = 10, DEX = -5, LUK = -5},
		passiveName = "Sacred Bond",
		passiveActivation = "Cleric commits a Healing-tagged Skill",
		passiveEffect = "Healing potency +15%; if target is below 30% max HP, healing potency +25% instead",
		passiveRangePattern = "Self (applied to caster's healing output)",
		passiveDuration = "Per Skill resolution",
		passiveFrequency = "Per eligible Healing Skill",
		passiveStacking = "Does not stack; uses highest applicable tier",
		breakBehavior = "Disabled by Break; pre-existing snapshot effects persist only where explicitly stated",
		skillChoices = {"SKL-CONSECRATE", "SKL-MENDING-RAIN", "SKL-LIFE-LINK"},
		activeChoiceCount = 1,
		augmentSlotRule = "Standard 2 Augment Slots",
		associatedSkillFamily = "Healing, Support",
		scarcity = "Acquisition scarcity only; exact band pending",
	},
	["DOC-ELEMENTALIST"] = {
		name = "Elementalist",
		identity = "Raw elemental magic damage",
		statPackage = {STR = -15, AGI = -5, INT = 15, VIT = -10, DEX = 10, LUK = 5},
		passiveName = "Elemental Convergence",
		passiveActivation = "Elementalist commits a Skill with an element tag (Fire, Ice, Water, Electric, Earth, Poison, Dark, Holy)",
		passiveEffect = "Skill final damage +12%; if the previous Skill this battle used a different element tag, bonus increases to +18% instead",
		passiveRangePattern = "Self",
		passiveDuration = "Per Skill resolution",
		passiveFrequency = "Per eligible elemental Skill",
		passiveStacking = "Does not stack; tracks last-used element tag per battle",
		breakBehavior = "Disabled by Break; pre-existing snapshot effects persist only where explicitly stated",
		skillChoices = {"SKL-PYROCLASM", "SKL-GLACIAL-WAVE", "SKL-STORM-BARRAGE"},
		activeChoiceCount = 1,
		augmentSlotRule = "Standard 2 Augment Slots",
		associatedSkillFamily = "Direct Damage, Elemental",
		scarcity = "Acquisition scarcity only; exact band pending",
	},
	["DOC-SENTINEL"] = {
		name = "Sentinel",
		identity = "Reactive punishment and counterplay",
		statPackage = {STR = 10, AGI = -5, INT = -10, VIT = 15, DEX = -5, LUK = -5},
		passiveName = "Vengeful Riposte",
		passiveActivation = "Sentinel takes direct HP damage from an enemy Skill while standing",
		passiveEffect = "Sentinel's next Direct Damage Skill this round gains +20% final damage; effect consumed on first eligible Skill commitment or at round end",
		passiveRangePattern = "Self",
		passiveDuration = "Until consumed or round end",
		passiveFrequency = "Once per incoming hit (refreshes if hit again before consuming)",
		passiveStacking = "Does not stack; refreshes duration. Only one charge stored at a time.",
		breakBehavior = "Disabled by Break; pre-existing snapshot effects persist only where explicitly stated",
		skillChoices = {"SKL-COUNTER-STANCE", "SKL-RETRIBUTION-SHELL", "SKL-SHATTER-BLOW"},
		activeChoiceCount = 1,
		augmentSlotRule = "Standard 2 Augment Slots",
		associatedSkillFamily = "Direct Damage, Utility",
		scarcity = "Acquisition scarcity only; exact band pending",
	},
	["DOC-GEOMANCER"] = {
		name = "Geomancer",
		identity = "Terrain manipulation and area denial",
		statPackage = {STR = -10, AGI = -10, INT = 10, VIT = 5, DEX = 10, LUK = -5},
		passiveName = "Terrain Mastery",
		passiveActivation = "Geomancer commits a Skill that creates or modifies terrain",
		passiveEffect = "Created terrain effects last +1 turn; terrain damage dealt by Geomancer-owned terrain +20%",
		passiveRangePattern = "Geomancer-owned terrain effects",
		passiveDuration = "Applied at terrain creation",
		passiveFrequency = "Per eligible terrain-creating Skill",
		passiveStacking = "Does not stack on same terrain instance; applies independently to each new terrain",
		breakBehavior = "Disabled by Break; pre-existing terrain already created retains extended duration",
		skillChoices = {"SKL-FISSURE-LINE", "SKL-IGNITE-GROUND", "SKL-STATIC-FIELD"},
		activeChoiceCount = 1,
		augmentSlotRule = "Standard 2 Augment Slots",
		associatedSkillFamily = "Direct Damage, Utility, Terrain",
		scarcity = "Acquisition scarcity only; exact band pending",
	},
	["DOC-SHIELDBEARER"] = {
		name = "Shieldbearer",
		identity = "Shield-focused tanking and party protection",
		statPackage = {STR = 5, AGI = -10, INT = -5, VIT = 15, DEX = 5, LUK = -10},
		passiveName = "Aegis Protocol",
		passiveActivation = "Shieldbearer has a shield equipped in off-hand",
		passiveEffect = "Direct damage received -12%; when Shieldbearer takes damage while Guarding, next Skill committed this round has RT Cost -25%",
		passiveRangePattern = "Self",
		passiveDuration = "Passive (DR); RT reduction until consumed or round end",
		passiveFrequency = "DR: continuous while shield equipped. RT reduction: once per Guard-damage event.",
		passiveStacking = "RT reduction does not stack; refreshes on new Guard-damage event.",
		breakBehavior = "Disabled by Break; pre-existing snapshot effects persist only where explicitly stated",
		skillChoices = {"SKL-BULWARK-FIELD", "SKL-VITAL-BARRIER", "SKL-ARCANE-BARRIER"},
		activeChoiceCount = 1,
		augmentSlotRule = "Standard 2 Augment Slots",
		associatedSkillFamily = "Shield, Buff, Utility",
		scarcity = "Acquisition scarcity only; exact band pending",
	},
	["DOC-ASSASSIN"] = {
		name = "Assassin",
		identity = "Burst single-target damage and repositioning",
		statPackage = {STR = 5, AGI = 15, INT = -15, VIT = -15, DEX = 10},
		passiveName = "Killing Intent",
		passiveActivation = "Assassin attacks a target that has not yet acted this round",
		passiveEffect = "Direct Damage Skill final damage +20% against targets that have not taken a turn this round",
		passiveRangePattern = "Self",
		passiveDuration = "Per Skill resolution",
		passiveFrequency = "Per eligible Skill against qualifying target",
		passiveStacking = "Does not stack; binary check per target",
		breakBehavior = "Disabled by Break; pre-existing snapshot effects persist only where explicitly stated",
		skillChoices = {"SKL-LUNGE", "SKL-VANISHING-STEP", "SKL-TWIN-FANGS"},
		activeChoiceCount = 1,
		augmentSlotRule = "Standard 2 Augment Slots",
		associatedSkillFamily = "Direct Damage, Utility",
		scarcity = "Acquisition scarcity only; exact band pending",
	},
	["DOC-PALADIN"] = {
		name = "Paladin",
		identity = "Holy tank-healer hybrid",
		statPackage = {STR = 5, AGI = -10, INT = 5, VIT = 10, DEX = -5, LUK = -5},
		passiveName = "Divine Aegis",
		passiveActivation = "Paladin commits a Holy-tagged or Healing-tagged Skill",
		passiveEffect = "After resolution, Paladin gains +10% damage reduction for 1 turn; if the Skill healed an ally, that ally also gains +10% damage reduction for 1 turn",
		passiveRangePattern = "Self and healed ally",
		passiveDuration = "1 turn after Skill resolution",
		passiveFrequency = "Per eligible Holy or Healing Skill",
		passiveStacking = "Does not stack; refreshes duration",
		breakBehavior = "Disabled by Break; pre-existing snapshot effects persist only where explicitly stated",
		skillChoices = {"SKL-BENEDICTION", "SKL-PURGE", "SKL-BLINDING-FLASH"},
		activeChoiceCount = 1,
		augmentSlotRule = "Standard 2 Augment Slots",
		associatedSkillFamily = "Healing, Buff, Holy, Debuff",
		scarcity = "Acquisition scarcity only; exact band pending",
	},
	["DOC-MONK"] = {
		name = "Monk",
		identity = "Unarmed martial arts and multi-hit",
		statPackage = {STR = 10, AGI = 10, INT = -15, VIT = 5, DEX = 5, LUK = -15},
		passiveName = "Flowing Strikes",
		passiveActivation = "Monk commits a Direct Damage Skill that hits the same target as the previous action this turn",
		passiveEffect = "Second and subsequent Direct Damage Skills against the same target this turn gain +10% final damage per prior hit (cap +30%)",
		passiveRangePattern = "Self",
		passiveDuration = "Current unit turn; resets on new turn",
		passiveFrequency = "Per eligible consecutive hit on same target",
		passiveStacking = "+10% per prior hit on same target this turn, max +30% (4th hit onwards)",
		breakBehavior = "Disabled by Break; pre-existing snapshot effects persist only where explicitly stated",
		skillChoices = {"SKL-FLURRY-OF-BLADES", "SKL-GALE-THRUST", "SKL-BATTLE-FURY"},
		activeChoiceCount = 1,
		augmentSlotRule = "Standard 2 Augment Slots",
		associatedSkillFamily = "Direct Damage, Buff, Physical",
		scarcity = "Acquisition scarcity only; exact band pending",
	},
	["DOC-PLAGUE-DOCTOR"] = {
		name = "Plague Doctor",
		identity = "Poison and dark debuff specialist with emergency healing",
		statPackage = {STR = -10, AGI = -5, INT = 10, VIT = 5, DEX = -5, LUK = 5},
		passiveName = "Virulence",
		passiveActivation = "Plague Doctor applies a Poison or Dark-tagged debuff to an enemy",
		passiveEffect = "Poison and Venom tick damage dealt by this unit +25%; Dark-tagged debuffs applied by this unit ignore 15% of target's Debuff Resistance",
		passiveRangePattern = "Source-owned debuffs",
		passiveDuration = "Per debuff application and subsequent ticks",
		passiveFrequency = "Per eligible application",
		breakBehavior = "Disabled by Break; pre-existing snapshot effects persist only where explicitly stated",
		skillChoices = {"SKL-DARK-RESTORATION", "SKL-FESTERING-WOUND", "SKL-MIASMA-CLOUD"},
		activeChoiceCount = 1,
		augmentSlotRule = "Standard 2 Augment Slots",
		associatedSkillFamily = "Debuff, Healing, Poison, Dark",
		scarcity = "Acquisition scarcity only; exact band pending",
	},
	["DOC-ENCHANTER"] = {
		name = "Enchanter",
		identity = "Buff amplification and duration extension",
		statPackage = {STR = -15, AGI = 5, INT = 10, VIT = -5, DEX = -5, LUK = 10},
		passiveName = "Lingering Enchantment",
		passiveActivation = "Enchanter applies a Buff to any ally (including self)",
		passiveEffect = "Buff duration +1 turn; buff numerical effects +10% (multiplicative with base values)",
		passiveRangePattern = "Enchanter-owned buffs",
		passiveDuration = "Applied at buff creation",
		passiveFrequency = "Per eligible buff application",
		passiveStacking = "Does not stack on same buff instance; applies independently to each new buff",
		breakBehavior = "Disabled by Break; pre-existing buffs already extended retain their duration",
		skillChoices = {"SKL-INVIGORATE", "SKL-ARCANE-RENEWAL", "SKL-EMPOWERING-AURA"},
		activeChoiceCount = 1,
		augmentSlotRule = "Standard 2 Augment Slots",
		associatedSkillFamily = "Buff, Utility",
		scarcity = "Acquisition scarcity only; exact band pending",
	},
	["DOC-DRAGOON"] = {
		name = "Dragoon",
		identity = "Aerial strike specialist and jump combat",
		statPackage = {STR = 15, AGI = 5, INT = -15, VIT = 5, DEX = -5, LUK = -5},
		passiveName = "Aerial Supremacy",
		passiveActivation = "Dragoon commits a Direct Damage Skill while at higher elevation than target, or targets a tile from maximum jump height",
		passiveEffect = "Direct Damage Skill final damage +20%; ignore 50% of target's positional defense bonus from elevation",
		passiveRangePattern = "Self",
		passiveDuration = "Per Skill resolution",
		passiveFrequency = "Per eligible Skill from elevation advantage",
		passiveStacking = "Does not stack",
		breakBehavior = "Disabled by Break; pre-existing snapshot effects persist only where explicitly stated",
		skillChoices = {"SKL-DECIMATING-SWING", "SKL-SKYFALL-LANCE", "SKL-DRAGON-DIVE"},
		activeChoiceCount = 1,
		augmentSlotRule = "Standard 2 Augment Slots",
		associatedSkillFamily = "Direct Damage, Physical, Utility",
		scarcity = "Acquisition scarcity only; exact band pending",
	},
	["DOC-REAPER"] = {
		name = "Reaper",
		identity = "Dark melee sustain through enemy HP drain",
		statPackage = {STR = 10, AGI = 5, INT = 5, VIT = -10, DEX = -15, LUK = 5},
		passiveName = "Soul Rend",
		passiveActivation = "Reaper deals Dark-tagged HP damage to an enemy",
		passiveEffect = "Recover HP equal to 12% of Dark damage dealt; if target is defeated by this damage, recover an additional 10% max HP",
		passiveRangePattern = "Self",
		passiveDuration = "Per damage instance",
		passiveFrequency = "Per eligible Dark damage dealt",
		passiveStacking = "None; recovery per instance",
		breakBehavior = "Disabled by Break; pre-existing snapshot effects persist only where explicitly stated",
		skillChoices = {"SKL-BLOOD-PRICE", "SKL-SHADOW-RAKE", "SKL-SIPHON-PULSE"},
		activeChoiceCount = 1,
		augmentSlotRule = "Standard 2 Augment Slots",
		associatedSkillFamily = "Direct Damage, Dark, Healing",
		scarcity = "Acquisition scarcity only; exact band pending",
	},
	["DOC-TEMPLAR"] = {
		name = "Templar",
		identity = "Holy damage dealer and anti-undead specialist",
		statPackage = {STR = 10, AGI = -5, INT = 10, VIT = -5, DEX = -5, LUK = -5},
		passiveName = "Radiant Judgment",
		passiveActivation = "Templar deals Holy-tagged damage",
		passiveEffect = "Holy damage dealt +15%; against Undead targets, Holy damage dealt +30% instead (replaces, does not stack with base +15%)",
		passiveRangePattern = "Self",
		passiveDuration = "Per damage instance",
		passiveFrequency = "Per eligible Holy damage dealt",
		breakBehavior = "Disabled by Break; pre-existing snapshot effects persist only where explicitly stated",
		skillChoices = {"SKL-SEAL-OF-SILENCE", "SKL-HOLY-SMITE", "SKL-SANCTIFY"},
		activeChoiceCount = 1,
		augmentSlotRule = "Standard 2 Augment Slots",
		associatedSkillFamily = "Direct Damage, Holy, Debuff",
		scarcity = "Acquisition scarcity only; exact band pending",
	},
	["DOC-STORMBRINGER"] = {
		name = "Stormbringer",
		identity = "Electric chain damage and crowd control",
		statPackage = {STR = -10, AGI = 5, INT = 15, VIT = -15, DEX = 5},
		passiveName = "Conductivity",
		passiveActivation = "Stormbringer's Electric-tagged Skill hits a target that is Wet",
		passiveEffect = "Electric damage +25% against Wet targets; Electric Skills that hit multiple targets deal +5% final damage per additional target hit (cap +20%)",
		passiveRangePattern = "Self",
		passiveDuration = "Per Skill resolution",
		passiveFrequency = "Per eligible Electric Skill",
		passiveStacking = "Wet bonus and multi-target bonus stack additively",
		breakBehavior = "Disabled by Break; pre-existing snapshot effects persist only where explicitly stated",
		skillChoices = {"SKL-CHAIN-SPARK", "SKL-VOLTAIC-CHAIN", "SKL-THUNDERCLAP"},
		activeChoiceCount = 1,
		augmentSlotRule = "Standard 2 Augment Slots",
		associatedSkillFamily = "Direct Damage, Electric, Debuff",
		scarcity = "Acquisition scarcity only; exact band pending",
	},
	["DOC-GUNNER"] = {
		name = "Gunner",
		identity = "Ranged physical multi-hit and suppression",
		statPackage = {STR = 5, AGI = -5, INT = -15, VIT = -5, DEX = 15, LUK = 5},
		passiveName = "Suppressive Fire",
		passiveActivation = "Gunner commits a ranged Direct Damage Skill (range ≥ 3)",
		passiveEffect = "If Skill hits, target's movement range is reduced by 1 for their next turn; if Skill is multi-hit, each additional hit extends movement reduction by 1 turn (cap 3 turns)",
		passiveRangePattern = "Target",
		passiveDuration = "1 turn per hit (cap 3 turns)",
		passiveFrequency = "Per eligible ranged Skill",
		passiveStacking = "Duration extends per multi-hit; does not increase movement reduction amount",
		breakBehavior = "Disabled by Break; pre-existing snapshot effects persist only where explicitly stated",
		skillChoices = {"SKL-RECOIL-SHOT", "SKL-CRIPPLING-SHOT", "SKL-BARRAGE"},
		activeChoiceCount = 1,
		augmentSlotRule = "Standard 2 Augment Slots",
		associatedSkillFamily = "Direct Damage, Physical, Debuff",
		scarcity = "Acquisition scarcity only; exact band pending",
	},
	["DOC-WARDEN"] = {
		name = "Warden",
		identity = "Earth/nature defensive support and area control",
		statPackage = {STR = -5, AGI = -10, INT = 5, VIT = 15, DEX = 5, LUK = -10},
		passiveName = "Earthen Resilience",
		passiveActivation = "Warden and allies within Range 2 are standing on natural terrain (not player-created terrain effects)",
		passiveEffect = "Affected allies gain +8% damage reduction and +1 movement cost for enemies entering tiles within range (area denial)",
		passiveRangePattern = "Aura Range 2",
		passiveDuration = "Passive",
		passiveFrequency = "Continuous while condition true",
		passiveStacking = "Multiple sources use strongest; does not stack",
		breakBehavior = "Disabled by Break; pre-existing snapshot effects persist only where explicitly stated",
		skillChoices = {"SKL-EARTHEN-LANCE", "SKL-SHATTER-POINT", "SKL-NATURES-GRASP"},
		activeChoiceCount = 1,
		augmentSlotRule = "Standard 2 Augment Slots",
		associatedSkillFamily = "Direct Damage, Debuff, Earth, Utility",
		scarcity = "Acquisition scarcity only; exact band pending",
	},
	["DOC-SKIRMISHER"] = {
		name = "Skirmisher",
		identity = "Mobile melee with bleed and hit-and-run",
		statPackage = {STR = 5, AGI = 10, INT = -10, VIT = -5, DEX = 10, LUK = -10},
		passiveName = "Harrying Strikes",
		passiveActivation = "Skirmisher has moved at least 2 tiles this turn before committing a Direct Damage Skill",
		passiveEffect = "Direct Damage Skill gains +15% final damage and applies 1 stack of Bleed to target regardless of other effects",
		passiveRangePattern = "Self",
		passiveDuration = "Per eligible Skill this turn",
		passiveFrequency = "Per eligible Skill committed after movement",
		passiveStacking = "Bleed stacks normally per Bleed rules; damage bonus does not stack",
		breakBehavior = "Disabled by Break; pre-existing snapshot effects persist only where explicitly stated",
		skillChoices = {"SKL-HEMORRHAGE", "SKL-RENDING-SLASH", "SKL-NULL-STRIKE"},
		activeChoiceCount = 1,
		augmentSlotRule = "Standard 2 Augment Slots",
		associatedSkillFamily = "Direct Damage, Physical, Debuff",
		scarcity = "Acquisition scarcity only; exact band pending",
	},
}

return table.freeze(DoctrineData)
