-- RegionData.lua
-- CTRBLXAI | Slice 5 -- Procedural Map Generation
--
-- Generated from CTRBLXAI.db regions table.
-- DO NOT EDIT MANUALLY -- regenerate from DB if rules change.
-- objectWeights updated 2026-10-06 from the Designer's region-pool expansion
-- (>=10 real objects per region, no region-exclusive objects). DB write pending.

local RegionData = {}

RegionData["Grassland"] = {
	id = "Grassland",
	identity = "Open natural field",
	minSize = 20,
	maxSize = 250,
	terrainWeights = {
		Grassland = 55,
		Clear = 25,
		["Clover Field"] = 5,
		Mud = 5,
		Rocky = 5,
		["Shallow Water"] = 5,
	},
	objectWeights = {
		["Treasure Chest"] = 6,
		Campfire = 5,
		["Rally Flag"] = 4,
		["Healing Spring"] = 3,
		["Bear Trap"] = 3,
		["Snare Trap"] = 3,
		["Swan Pond"] = 2,
		["Mysterious Boulder"] = 2,
		["War Horn"] = 2,
		["Idol of Fortune"] = 1,
		["Angel Statue"] = 1,
	},
	hazardWeights = {
		Burning = 2,
		Vines = 1,
	},
	poiTypes = { "Campfire", "Chest", "Rally Flag" },
	specialRules = "Good baseline region.",
}

RegionData["Farmland"] = {
	id = "Farmland",
	identity = "Rural cultivated land",
	minSize = 20,
	maxSize = 160,
	terrainWeights = {
		Grassland = 35,
		Clear = 30,
		Road = 15,
		["Wooden Floor"] = 5,
		Mud = 10,
		["Shallow Water"] = 5,
	},
	objectWeights = {
		Campfire = 6,
		["Treasure Chest"] = 5,
		["Bear Trap"] = 4,
		["Snare Trap"] = 4,
		["Swan Pond"] = 3,
		Tavern = 2,
		["Burning Cauldron"] = 2,
		["Healing Spring"] = 2,
		["Rally Flag"] = 2,
		["Idol of Fortune"] = 1,
		Mimic = 1,
	},
	hazardWeights = {
		Burning = 2,
		["Bear Trap"] = 1,
	},
	poiTypes = { "Chest", "Trading Post", "Campfire" },
	specialRules = "Needs simple object substitutions in Roblox if non-catalog objects are missing.",
}

RegionData["Village"] = {
	id = "Village",
	identity = "Settlement cluster",
	minSize = 25,
	maxSize = 160,
	terrainWeights = {
		Clear = 35,
		Rocky = 20,
		["Wooden Floor"] = 20,
		Grassland = 15,
		Mud = 5,
		Metal = 5,
	},
	objectWeights = {
		Tavern = 5,
		["Treasure Chest"] = 4,
		["Black Market"] = 3,
		Campfire = 4,
		Forge = 3,
		["Burning Cauldron"] = 3,
		["Fountain of Fortune"] = 2,
		["Crystal Ball"] = 2,
		["Potion Desk"] = 1,
		["Healing Spring"] = 2,
		["Rally Flag"] = 2,
		Mimic = 1,
	},
	hazardWeights = {
		Burning = 2,
		Oily = 1,
	},
	poiTypes = { "Black Market", "Trading Post", "Tavern", "Scholar", "Chest" },
	specialRules = "Objects occupy tiles. NPC/merchant represented as objects.",
}

RegionData["Forest"] = {
	id = "Forest",
	identity = "Dense woods and clearings",
	minSize = 30,
	maxSize = 220,
	terrainWeights = {
		Grassland = 35,
		Clear = 20,
		Mud = 10,
		Rocky = 10,
		["Clover Field"] = 5,
		["Shallow Water"] = 5,
		["Forest Floor"] = 15,
	},
	objectWeights = {
		["Bear Trap"] = 5,
		["Snare Trap"] = 5,
		Campfire = 4,
		["Treasure Chest"] = 4,
		["Witch Hut"] = 3,
		["Healing Spring"] = 3,
		["Mysterious Boulder"] = 3,
		["Runed Boulder"] = 2,
		["Swan Pond"] = 2,
		Mimic = 2,
		["Magic Spring"] = 1,
		["Glow Crystal"] = 1,
	},
	hazardWeights = {
		["Bear Trap"] = 5,
		["Snare Trap"] = 4,
		Vines = 5,
		Burning = 1,
	},
	poiTypes = { "Witch Hut", "Campfire", "Chest", "Healing Spring" },
	specialRules = "LAN validation prevents total blockage in required lanes.",
}

RegionData["Clearing"] = {
	id = "Clearing",
	identity = "Open pocket inside forest",
	minSize = 10,
	maxSize = 80,
	terrainWeights = {
		Clear = 35,
		Grassland = 35,
		["Clover Field"] = 10,
		Mud = 10,
		Rocky = 5,
		["Shallow Water"] = 5,
	},
	objectWeights = {
		Campfire = 5,
		["Healing Spring"] = 5,
		["Treasure Chest"] = 5,
		["Swan Pond"] = 3,
		["Magic Spring"] = 3,
		["Mysterious Boulder"] = 2,
		["Angel Statue"] = 2,
		["Bear Trap"] = 2,
		["Witch Hut"] = 1,
		["Idol of Fortune"] = 1,
		["Star Axis"] = 1,
	},
	hazardWeights = {
		Vines = 2,
		["Bear Trap"] = 1,
	},
	poiTypes = { "Campfire", "Chest", "Healing Spring" },
	specialRules = "Useful transition region.",
}

RegionData["Rocky"] = {
	id = "Rocky",
	identity = "Stone-heavy outcrop",
	minSize = 20,
	maxSize = 220,
	terrainWeights = {
		Rocky = 50,
		["Cracked Ground"] = 15,
		Clear = 15,
		Mud = 5,
		Sand = 5,
		Grassland = 10,
	},
	objectWeights = {
		["Stone Pillar"] = 7,
		["Runed Boulder"] = 5,
		["Mysterious Boulder"] = 4,
		["Treasure Chest"] = 3,
		["Spike Trap"] = 3,
		Ballista = 3,
		["Land Mine"] = 2,
		["Bomb Barrel"] = 2,
		Obelisk = 2,
		Campfire = 2,
		Mimic = 1,
	},
	hazardWeights = {
		["Cracked Ground"] = 5,
		["Earthquake Mark"] = 2,
	},
	poiTypes = { "Chest", "Stone Pillar", "Ballista" },
	specialRules = "Highlands/ruins core region.",
}

RegionData["Mountain Pass"] = {
	id = "Mountain Pass",
	identity = "Ridge/pass area",
	minSize = 20,
	maxSize = 180,
	terrainWeights = {
		Rocky = 45,
		Clear = 20,
		["Cracked Ground"] = 15,
		Grassland = 10,
		Mud = 5,
		Sand = 5,
	},
	objectWeights = {
		["Stone Pillar"] = 8,
		Ballista = 4,
		["War Banner"] = 3,
		["War Horn"] = 3,
		["Rally Flag"] = 3,
		["Runed Boulder"] = 3,
		["Spike Trap"] = 3,
		Catapult = 2,
		["Treasure Chest"] = 3,
		Campfire = 2,
		["Land Mine"] = 2,
		["Dragon Utopia"] = 1,
		["Ice Spike"] = 2,
	},
	hazardWeights = {
		["Cliff Edge"] = 8,
		["Cracked Ground"] = 6,
	},
	poiTypes = { "Watchtower", "Chest", "War Banner" },
	specialRules = "Likely uses LAN heavily to ensure traversal.",
}

RegionData["Riverbank"] = {
	id = "Riverbank",
	identity = "Water edge and crossing support",
	minSize = 15,
	maxSize = 160,
	terrainWeights = {
		["Shallow Water"] = 25,
		["Deep Water"] = 10,
		Mud = 20,
		Grassland = 20,
		Clear = 15,
		Rocky = 10,
	},
	objectWeights = {
		["Swan Pond"] = 5,
		["Healing Spring"] = 5,
		Campfire = 4,
		["Treasure Chest"] = 4,
		["Magic Spring"] = 3,
		["Snare Trap"] = 3,
		["Bear Trap"] = 2,
		["Mysterious Boulder"] = 2,
		["Witch Hut"] = 1,
		["Oil Sluice"] = 1,
		["Fountain of Fortune"] = 1,
	},
	hazardWeights = {
		Wet = 10,
		["Tar Pit"] = 1,
	},
	poiTypes = { "Bridge", "Chest", "Healing Spring" },
	specialRules = "Water systems should be coherent.",
}

RegionData["Marsh"] = {
	id = "Marsh",
	identity = "Swamp/wet ground region",
	minSize = 20,
	maxSize = 200,
	terrainWeights = {
		Swamp = 35,
		Mud = 25,
		["Shallow Water"] = 20,
		Grassland = 10,
		Rocky = 10,
	},
	objectWeights = {
		["Bear Trap"] = 5,
		["Snare Trap"] = 5,
		["Witch Hut"] = 4,
		["Cursed Statue"] = 3,
		["Burning Cauldron"] = 3,
		["Swan Pond"] = 2,
		["Cursed Chest"] = 2,
		["Magic Spring"] = 2,
		["Necro Tome Stand"] = 1,
		["Treasure Chest"] = 2,
		["Oil Sluice"] = 1,
		["Glow Crystal"] = 1,
	},
	hazardWeights = {
		Wet = 10,
		["Poison Cloud"] = 3,
		Vines = 3,
	},
	poiTypes = { "Witch Hut", "Cursed Statue", "Chest" },
	specialRules = "Poor mobility expected outside required LAN.",
}

RegionData["Frozen Lake"] = {
	id = "Frozen Lake",
	identity = "Frozen/wet tundra feature",
	minSize = 20,
	maxSize = 220,
	terrainWeights = {
		Ice = 45,
		["Shallow Water"] = 20,
		Rocky = 15,
		Clear = 10,
		Grassland = 10,
	},
	objectWeights = {
		["Ice Spike"] = 7,
		Campfire = 5,
		["Magic Spring"] = 4,
		["Treasure Chest"] = 3,
		["Stone Pillar"] = 3,
		["Snare Trap"] = 3,
		["Runed Boulder"] = 2,
		["Healing Spring"] = 2,
		["Swan Pond"] = 2,
		["Mysterious Boulder"] = 2,
		["Star Axis"] = 1,
		["Glow Crystal"] = 1,
	},
	hazardWeights = {
		Frozen = 10,
		["Severe Hail Mark"] = 3,
	},
	poiTypes = { "Campfire", "Chest", "Magic Spring" },
	specialRules = "Ice/water coherence important.",
}

RegionData["Volcanic Rock"] = {
	id = "Volcanic Rock",
	identity = "Volcano stone field",
	minSize = 20,
	maxSize = 220,
	terrainWeights = {
		Rocky = 45,
		Molten = 15,
		Clear = 20,
		Sand = 15,
		["Cracked Ground"] = 5,
	},
	objectWeights = {
		["Steam Valve"] = 6,
		["Bomb Barrel"] = 5,
		["Stone Pillar"] = 4,
		["Spike Trap"] = 3,
		["Land Mine"] = 3,
		Forge = 3,
		["Runed Boulder"] = 2,
		["Treasure Chest"] = 2,
		["Oil Sluice"] = 2,
		["Dragon Utopia"] = 2,
		["Chaos Statue"] = 1,
		["Burning Cauldron"] = 1,
	},
	hazardWeights = {
		Burning = 8,
		["Molten Hazard"] = 10,
		Steam = 4,
	},
	poiTypes = { "Steam Valve", "Chest", "Dragon Utopia" },
	specialRules = "Hazards frequent. Required battleflow still validated.",
}

RegionData["Lava Channel"] = {
	id = "Lava Channel",
	identity = "Molten feature band",
	minSize = 10,
	maxSize = 140,
	terrainWeights = {
		Molten = 40,
		Rocky = 35,
		Clear = 15,
		Sand = 10,
	},
	objectWeights = {
		["Steam Valve"] = 6,
		["Oil Sluice"] = 4,
		["Bomb Barrel"] = 4,
		["Stone Pillar"] = 3,
		Forge = 3,
		["Land Mine"] = 2,
		["Spike Trap"] = 2,
		["Dragon Utopia"] = 2,
		["Chaos Statue"] = 2,
		["Treasure Chest"] = 2,
		["Blood Fountain"] = 1,
	},
	hazardWeights = {
		Burning = 10,
		Steam = 5,
	},
	poiTypes = { "Bridge", "Steam Valve", "Chest" },
	specialRules = "Similar to WAT but region-owned.",
}

RegionData["Ruins"] = {
	id = "Ruins",
	identity = "Broken ancient structures",
	minSize = 25,
	maxSize = 220,
	terrainWeights = {
		Rocky = 30,
		Clear = 20,
		["Wooden Floor"] = 15,
		Mud = 10,
		["Cracked Ground"] = 10,
		Grassland = 15,
	},
	objectWeights = {
		["Stone Pillar"] = 7,
		["Treasure Chest"] = 5,
		Mimic = 4,
		Obelisk = 3,
		["Runed Boulder"] = 3,
		["Spike Trap"] = 3,
		["Bomb Barrel"] = 2,
		["Angel Statue"] = 2,
		["Cursed Statue"] = 2,
		Astrolabe = 2,
		["Pandora's Box"] = 1,
		["Eye of the Magi"] = 1,
		["Necro Tome Stand"] = 1,
	},
	hazardWeights = {
		["Cracked Ground"] = 5,
		Burning = 2,
		["Poison Cloud"] = 1,
	},
	poiTypes = { "Tomb", "Library", "Scholar", "Chest", "Mimic" },
	specialRules = "Interactive objects common.",
}

RegionData["Castle Courtyard"] = {
	id = "Castle Courtyard",
	identity = "Open fortified area",
	minSize = 25,
	maxSize = 220,
	terrainWeights = {
		Rocky = 35,
		Metal = 15,
		["Wooden Floor"] = 15,
		Clear = 20,
		Grassland = 10,
		Road = 5,
	},
	objectWeights = {
		Ballista = 6,
		Catapult = 5,
		["War Banner"] = 4,
		["Stone Pillar"] = 4,
		["Rally Flag"] = 3,
		["War Horn"] = 3,
		["Bomb Barrel"] = 3,
		["Spike Trap"] = 2,
		["Treasure Chest"] = 3,
		Forge = 2,
		["Black Market"] = 1,
		["Angel Statue"] = 1,
	},
	hazardWeights = {
		["Bomb Barrel"] = 3,
		Burning = 1,
	},
	poiTypes = { "Ballista", "War Banner", "Chest", "Black Market" },
	specialRules = "Strong defensive object distribution.",
}

RegionData["Castle Interior"] = {
	id = "Castle Interior",
	identity = "Indoor/fortified floor area",
	minSize = 15,
	maxSize = 140,
	terrainWeights = {
		Metal = 30,
		["Wooden Floor"] = 30,
		Rocky = 20,
		Clear = 15,
		Grassland = 5,
	},
	objectWeights = {
		["Treasure Chest"] = 5,
		["Stone Pillar"] = 4,
		["War Banner"] = 3,
		Forge = 3,
		Mimic = 3,
		["Bomb Barrel"] = 3,
		["Spike Trap"] = 3,
		Astrolabe = 2,
		["Crystal Ball"] = 2,
		["Angel Statue"] = 2,
		["Potion Desk"] = 1,
		["Pandora's Box"] = 1,
		["Eye of the Magi"] = 1,
		["Black Market"] = 1,
	},
	hazardWeights = {
		["Bomb Barrel"] = 3,
		Steam = 1,
	},
	poiTypes = { "Chest", "Marletto Tower", "Mercenary Camp" },
	specialRules = "May conflict with open templates unless LAN protected.",
}

RegionData["Graveyard"] = {
	id = "Graveyard",
	identity = "Tombs and death-themed objects",
	minSize = 15,
	maxSize = 140,
	terrainWeights = {
		["Tainted Ground"] = 20,
		Rocky = 25,
		Grassland = 20,
		Clear = 15,
		Mud = 10,
		["Magic Circle"] = 10,
	},
	objectWeights = {
		["Cursed Statue"] = 5,
		["Necro Tome Stand"] = 4,
		["Cursed Chest"] = 4,
		["Blood Fountain"] = 3,
		["Cover of Darkness"] = 3,
		["Stone Pillar"] = 3,
		Obelisk = 3,
		["Angel Statue"] = 2,
		Mimic = 2,
		["Spike Trap"] = 2,
		["Chaos Statue"] = 1,
		["Treasure Chest"] = 2,
	},
	hazardWeights = {
		["Dark Eclipse Mark"] = 3,
		["Poison Cloud"] = 2,
	},
	poiTypes = { "Warrior Tomb", "Cursed Statue", "Chest" },
	specialRules = "Pairs with Corrupted/Ruins.",
}

RegionData["Corrupted"] = {
	id = "Corrupted",
	identity = "Cursed magical patch",
	minSize = 20,
	maxSize = 180,
	terrainWeights = {
		["Tainted Ground"] = 40,
		["Magic Circle"] = 15,
		Swamp = 15,
		Rocky = 15,
		Mud = 10,
		Clear = 5,
	},
	objectWeights = {
		["Cursed Statue"] = 5,
		["Cover of Darkness"] = 4,
		["Chaos Statue"] = 4,
		["Blood Fountain"] = 3,
		["Necro Tome Stand"] = 3,
		["Cursed Chest"] = 3,
		["Stone Pillar"] = 2,
		["Witch Hut"] = 2,
		["Eye of the Magi"] = 2,
		Obelisk = 2,
		["Pandora's Box"] = 1,
		["Land Mine"] = 2,
	},
	hazardWeights = {
		["Poison Cloud"] = 4,
		["Dark Field"] = 6,
		["Hunger Virus Mark"] = 2,
	},
	poiTypes = { "Cursed Statue", "Altar", "Seer Hut", "Chest" },
	specialRules = "Resource denial/status theme.",
}

RegionData["Beach"] = {
	id = "Beach",
	identity = "Coastal sand/shore",
	minSize = 20,
	maxSize = 180,
	terrainWeights = {
		Sand = 45,
		["Shallow Water"] = 20,
		Clear = 15,
		Rocky = 10,
		Grassland = 5,
		Mud = 5,
	},
	objectWeights = {
		Campfire = 5,
		["Treasure Chest"] = 5,
		["Swan Pond"] = 4,
		["Healing Spring"] = 3,
		["Mysterious Boulder"] = 3,
		["Bomb Barrel"] = 2,
		["Snare Trap"] = 2,
		["Magic Spring"] = 2,
		["Idol of Fortune"] = 2,
		Mimic = 1,
		["Star Axis"] = 1,
	},
	hazardWeights = {
		Wet = 5,
		["Strong Wind Mark"] = 2,
	},
	poiTypes = { "Chest", "Campfire", "Boat" },
	specialRules = "Useful for coastline biome later.",
}

RegionData["Dock"] = {
	id = "Dock",
	identity = "Harbor/dock structures",
	minSize = 15,
	maxSize = 120,
	terrainWeights = {
		["Wooden Floor"] = 35,
		["Shallow Water"] = 25,
		Clear = 15,
		Rocky = 10,
		Metal = 5,
		["Deep Water"] = 10,
	},
	objectWeights = {
		["Bomb Barrel"] = 5,
		["Black Market"] = 4,
		Tavern = 4,
		["Treasure Chest"] = 4,
		["Oil Sluice"] = 3,
		Campfire = 3,
		Ballista = 2,
		["Snare Trap"] = 2,
		["Fountain of Fortune"] = 2,
		["Idol of Fortune"] = 2,
		Mimic = 1,
		Astrolabe = 1,
	},
	hazardWeights = {
		Wet = 5,
		Oily = 2,
	},
	poiTypes = { "Trading Post", "Black Market", "Chest" },
	specialRules = "City/coast hybrid.",
}

RegionData["Cave Chamber"] = {
	id = "Cave Chamber",
	identity = "Underground chamber content",
	minSize = 20,
	maxSize = 180,
	terrainWeights = {
		Rocky = 45,
		Clear = 20,
		Mud = 15,
		["Deep Water"] = 10,
		["Cracked Ground"] = 10,
	},
	objectWeights = {
		["Stone Pillar"] = 6,
		["Treasure Chest"] = 4,
		Mimic = 4,
		["Runed Boulder"] = 3,
		["Mysterious Boulder"] = 3,
		["Spike Trap"] = 3,
		["Magic Spring"] = 2,
		Campfire = 2,
		["Cursed Chest"] = 2,
		["Pandora's Box"] = 1,
		["Glow Crystal"] = 1,
		["Dragon Utopia"] = 1,
	},
	hazardWeights = {
		["Dark Pool"] = 5,
		["Earthquake Mark"] = 3,
	},
	poiTypes = { "Mimic", "Chest", "Campfire", "Tomb" },
	specialRules = "Topology special case.",
}

RegionData["Town"] = {
	id = "Town",
	identity = "Large market settlement (urban big sibling of Village)",
	minSize = 40,
	maxSize = 240,
	terrainWeights = {
		Clear = 35,
		Rocky = 30,
		["Wooden Floor"] = 20,
		Metal = 8,
		Grassland = 7,
	},
	objectWeights = {
		Tavern = 5,
		["Black Market"] = 4,
		["Treasure Chest"] = 4,
		["Fountain of Fortune"] = 3,
		Forge = 3,
		["Stone Pillar"] = 3,
		["Crystal Ball"] = 2,
		Astrolabe = 2,
		["Burning Cauldron"] = 2,
		["Idol of Fortune"] = 2,
		["Rally Flag"] = 2,
		["Eye of the Magi"] = 1,
		["Potion Desk"] = 1,
		["Bomb Barrel"] = 1,
		["Star Axis"] = 1,
	},
	hazardWeights = {
		Burning = 3,
		Oily = 2,
		["Bomb Barrel"] = 1,
	},
	poiTypes = { "Trading Post", "Tavern", "Black Market", "Den of Thieves", "Stables", "Fountain of Fortune", "Chest" },
	specialRules = "Authored 2026-10-02 (user request: a real 'big town' region; Village stays the small settlement). Denser and more paved than Village: buildings in blocks separated by a connected street network (Road/Clear) — streets should carry the LAN so buildings never wall off battleflow. Objects occupy tiles; NPC/merchant/guild services represented as objects. Stone Pillar = civic monument/colonnade in town squares (topples into the 4-tile span or crushes). Only spawn home for Den of Thieves, Stables, Mage Guild, Warrior Guild, Fountain of Fortune — keep each at 1-2 (strong free buffs, contestable by both sides). Min size 40, so it rarely fits a 20x20 map — mainly a 30x30/40x40 region. Pairs with Village, Farmland, Castle Courtyard, Dock. Suggested biome pools (Dev wires in code): Plains 5, Castle 10.",
}

return RegionData