-- TraitData.lua
-- Auto-generated Content Registry: Unit Traits (358 entries: perks + flaws)
-- Do not edit manually. Regenerate from CTRBLXAI.db (unit_traits table).
-- Phase 1: data + lookup only. Effect text is NOT interpreted here (Phase 2/3 wire gameplay).
-- CRITICAL: look traits up BY trait_id, never by name (duplicate names exist, e.g. 'Clumsy', 'Sluggish').

local TraitData = {}

-- Trait definitions, keyed by trait_id
TraitData.Traits = {
	["TRAIT-F-001"] = {
		kind = "flaw",
		pairId = "TRAIT-001",
		name = "Accessory Klutz",
		tier = "common",
		effect = "Halve the numerical Base and Bonus stats from Accessory armor (Passive effects excluded).",
		category = "Armor Mastery",
	},
	["TRAIT-F-002"] = {
		kind = "flaw",
		pairId = "TRAIT-002",
		name = "Glass Nerves",
		tier = "common",
		effect = "Deals 15% less damage while below half HP.",
		category = "General",
	},
	["TRAIT-F-003"] = {
		kind = "flaw",
		pairId = "TRAIT-003",
		name = "Thin Blood",
		tier = "common",
		effect = "Venom damage received +50%.",
		category = "Endurance",
	},
	["TRAIT-F-004"] = {
		kind = "flaw",
		pairId = "TRAIT-004",
		name = "Scrupulous",
		tier = "common",
		effect = "Deals 15% less damage when attacking from the side or behind.",
		category = "General",
	},
	["TRAIT-F-005"] = {
		kind = "flaw",
		pairId = "TRAIT-005",
		name = "Heavy Basics",
		tier = "common",
		effect = "Basic Attack costs 30% more weapon WT. Does not affect skills.",
		category = "General",
	},
	["TRAIT-F-006"] = {
		kind = "flaw",
		pairId = "TRAIT-006",
		name = "Mana-Starved",
		tier = "common",
		effect = "Loses 5% MP for each remaining AP at end of turn.",
		category = "General",
	},
	["TRAIT-F-007"] = {
		kind = "flaw",
		pairId = "TRAIT-007",
		name = "Cursed Wounds",
		tier = "common",
		effect = "Healing received -25%",
		category = "Support",
	},
	["TRAIT-F-008"] = {
		kind = "flaw",
		pairId = "TRAIT-008",
		name = "Body Klutz",
		tier = "common",
		effect = "Halve the numerical Base and Bonus stats from Body armor (Passive effects excluded).",
		category = "Armor Mastery",
	},
	["TRAIT-F-009"] = {
		kind = "flaw",
		pairId = "TRAIT-009",
		name = "Weak",
		tier = "common",
		effect = "STR -15%",
		category = "General",
	},
	["TRAIT-F-010"] = {
		kind = "flaw",
		pairId = "TRAIT-010",
		name = "Dim",
		tier = "common",
		effect = "INT -15%",
		category = "General",
	},
	["TRAIT-F-011"] = {
		kind = "flaw",
		pairId = "TRAIT-011",
		name = "Underdog",
		tier = "common",
		effect = "Damage inflicted to lower level targets -10%",
		category = "General",
	},
	["TRAIT-F-012"] = {
		kind = "flaw",
		pairId = "TRAIT-012",
		name = "Jinxed",
		tier = "common",
		effect = "LUK -15%",
		category = "General",
	},
	["TRAIT-F-013"] = {
		kind = "flaw",
		pairId = "TRAIT-013",
		name = "Claustrophobic",
		tier = "common",
		effect = "Damage inflicted -5% for each enemy within 2 range.",
		category = "Combat",
	},
	["TRAIT-F-014"] = {
		kind = "flaw",
		pairId = "TRAIT-014",
		name = "Dark Weakness",
		tier = "common",
		effect = "Takes 50% increased damage from Dark-tagged attacks.",
		category = "Element",
	},
	["TRAIT-F-015"] = {
		kind = "flaw",
		pairId = "TRAIT-015",
		name = "Shallow Well",
		tier = "common",
		effect = "20% less max MP from INT",
		category = "Intellect",
	},
	["TRAIT-F-016"] = {
		kind = "flaw",
		pairId = "TRAIT-016",
		name = "Exposed Armor",
		tier = "common",
		effect = "Defense from armor decreased by 20%",
		category = "General",
	},
	["TRAIT-F-017"] = {
		kind = "flaw",
		pairId = "TRAIT-017",
		name = "Clumsy",
		tier = "common",
		effect = "DEX -15%",
		category = "General",
	},
	["TRAIT-F-018"] = {
		kind = "flaw",
		pairId = "TRAIT-018",
		name = "Spendthrift",
		tier = "common",
		effect = "Skill MP cost increased by 20%",
		category = "General",
	},
	["TRAIT-F-019"] = {
		kind = "flaw",
		pairId = "TRAIT-019",
		name = "Electric Weakness",
		tier = "common",
		effect = "Takes 50% increased damage from Electric-tagged attacks.",
		category = "Element",
	},
	["TRAIT-F-020"] = {
		kind = "flaw",
		pairId = "TRAIT-020",
		name = "Slow Learner",
		tier = "common",
		effect = "Gains 10% less XP from battles than normal.",
		category = "General",
	},
	["TRAIT-F-021"] = {
		kind = "flaw",
		pairId = "TRAIT-021",
		name = "Feet Klutz",
		tier = "common",
		effect = "Halve the numerical Base and Bonus stats from Feet armor (Passive effects excluded).",
		category = "Armor Mastery",
	},
	["TRAIT-F-022"] = {
		kind = "flaw",
		pairId = "TRAIT-022",
		name = "Fire Weakness",
		tier = "common",
		effect = "Takes 50% increased damage from Fire-tagged attacks.",
		category = "Element",
	},
	["TRAIT-F-023"] = {
		kind = "flaw",
		pairId = "TRAIT-023",
		name = "Flammable",
		tier = "common",
		effect = "Burn damage received +50%.",
		category = "Endurance",
	},
	["TRAIT-F-024"] = {
		kind = "flaw",
		pairId = "TRAIT-024",
		name = "Gloves Klutz",
		tier = "common",
		effect = "Halve the numerical Base and Bonus stats from Gloves armor (Passive effects excluded).",
		category = "Armor Mastery",
	},
	["TRAIT-F-025"] = {
		kind = "flaw",
		pairId = "TRAIT-025",
		name = "Frail",
		tier = "common",
		effect = "20% less max HP from VIT",
		category = "General",
	},
	["TRAIT-F-026"] = {
		kind = "flaw",
		pairId = "TRAIT-026",
		name = "Head Klutz",
		tier = "common",
		effect = "Halve the numerical Base and Bonus stats from Head armor (Passive effects excluded).",
		category = "Armor Mastery",
	},
	["TRAIT-F-027"] = {
		kind = "flaw",
		pairId = "TRAIT-027",
		name = "Sickly",
		tier = "common",
		effect = "VIT -15%",
		category = "General",
	},
	["TRAIT-F-028"] = {
		kind = "flaw",
		pairId = "TRAIT-028",
		name = "Feather Strikes",
		tier = "common",
		effect = "20% of weapon WT is subtracted from base weapon damage",
		category = "Combat",
	},
	["TRAIT-F-029"] = {
		kind = "flaw",
		pairId = "TRAIT-029",
		name = "Stubby Legs",
		tier = "common",
		effect = "-1 Jump",
		category = "Precision",
	},
	["TRAIT-F-030"] = {
		kind = "flaw",
		pairId = "TRAIT-030",
		name = "Holy Weakness",
		tier = "common",
		effect = "Takes 50% increased damage from Holy-tagged attacks.",
		category = "Element",
	},
	["TRAIT-F-031"] = {
		kind = "flaw",
		pairId = "TRAIT-031",
		name = "Ice Weakness",
		tier = "common",
		effect = "Takes 50% increased damage from Ice-tagged attacks.",
		category = "Element",
	},
	["TRAIT-F-032"] = {
		kind = "flaw",
		pairId = "TRAIT-032",
		name = "Weak Stomach",
		tier = "common",
		effect = "Poison damage received +50%.",
		category = "Endurance",
	},
	["TRAIT-F-033"] = {
		kind = "flaw",
		pairId = "TRAIT-033",
		name = "Susceptible",
		tier = "common",
		effect = "Debuffs and negative status effects duration increased by 1 turn or 400 CT depending on duration basis.",
		category = "General",
	},
	["TRAIT-F-034"] = {
		kind = "flaw",
		pairId = "TRAIT-034",
		name = "Brittle Plating",
		tier = "common",
		effect = "20% of total non-weapon WT is subtracted from base armor",
		category = "Endurance",
	},
	["TRAIT-F-035"] = {
		kind = "flaw",
		pairId = "TRAIT-035",
		name = "Item Fumbler",
		tier = "common",
		effect = "Healing and Damaging items effect are reduced by 25%",
		category = "General",
	},
	["TRAIT-F-036"] = {
		kind = "flaw",
		pairId = "TRAIT-036",
		name = "Clumsy",
		tier = "common",
		effect = "Precision -10%",
		category = "General",
	},
	["TRAIT-F-037"] = {
		kind = "flaw",
		pairId = "TRAIT-037",
		name = "Unlucky",
		tier = "common",
		effect = "10% fortune penalty",
		category = "General",
	},
	["TRAIT-F-038"] = {
		kind = "flaw",
		pairId = "TRAIT-038",
		name = "Sluggish",
		tier = "common",
		effect = "AGI -15%",
		category = "General",
	},
	["TRAIT-F-039"] = {
		kind = "flaw",
		pairId = "TRAIT-039",
		name = "Merciful",
		tier = "common",
		effect = "Damage inflicted to targets suffering from debuff reduced by 10%",
		category = "General",
	},
	["TRAIT-F-040"] = {
		kind = "flaw",
		pairId = "TRAIT-040",
		name = "Hemophiliac",
		tier = "common",
		effect = "Bleed damage received +50%.",
		category = "Endurance",
	},
	["TRAIT-F-041"] = {
		kind = "flaw",
		pairId = "TRAIT-041",
		name = "Slow to Recover",
		tier = "common",
		effect = "Recovers with only 5% HP after battle; revive HP halved.",
		category = "General",
	},
	["TRAIT-F-042"] = {
		kind = "flaw",
		pairId = "TRAIT-042",
		name = "Restless",
		tier = "common",
		effect = "-1 range if unit did not move in previous turn.",
		category = "Tactical",
	},
	["TRAIT-F-043"] = {
		kind = "flaw",
		pairId = "TRAIT-043",
		name = "Weak Grip",
		tier = "common",
		effect = "Gear WT increased by 20%, subtracted from STR bonus",
		category = "General",
	},
	["TRAIT-F-044"] = {
		kind = "flaw",
		pairId = "TRAIT-044",
		name = "Acrophobic",
		tier = "common",
		effect = "Base Fall Damage received increased by half before VIT bonus",
		category = "General",
	},
	["TRAIT-F-045"] = {
		kind = "flaw",
		pairId = "TRAIT-045",
		name = "Squishy",
		tier = "common",
		effect = "Receive double collision damage. Units colliding with this unit take no collision damage.",
		category = "General",
	},
	["TRAIT-F-046"] = {
		kind = "flaw",
		pairId = "TRAIT-046",
		name = "Thin Skin",
		tier = "common",
		effect = "Takes 10% more damage.",
		category = "General",
	},
	["TRAIT-F-047"] = {
		kind = "flaw",
		pairId = "TRAIT-047",
		name = "Water Weakness",
		tier = "common",
		effect = "Takes 50% increased damage from Water-tagged attacks.",
		category = "Element",
	},
	["TRAIT-F-048"] = {
		kind = "flaw",
		pairId = "TRAIT-048",
		name = "Glass Nerves (Greater)",
		tier = "uncommon",
		effect = "Deals 20% less damage while below half HP.",
		category = "General",
	},
	["TRAIT-F-049"] = {
		kind = "flaw",
		pairId = "TRAIT-049",
		name = "Dull",
		tier = "uncommon",
		effect = "AGI -10%, LUK -10%",
		category = "General",
	},
	["TRAIT-F-050"] = {
		kind = "flaw",
		pairId = "TRAIT-050",
		name = "Exposed",
		tier = "uncommon",
		effect = "when attack target is at higher elevation, -8% damage per elevation difference",
		category = "General",
	},
	["TRAIT-F-051"] = {
		kind = "flaw",
		pairId = "TRAIT-051",
		name = "Thin Blood (Greater)",
		tier = "common",
		effect = "Venom damage received +60%.",
		category = "Endurance",
	},
	["TRAIT-F-052"] = {
		kind = "flaw",
		pairId = "TRAIT-052",
		name = "Scrupulous (Greater)",
		tier = "common",
		effect = "Deals 20% less damage when attacking from the side or behind.",
		category = "General",
	},
	["TRAIT-F-053"] = {
		kind = "flaw",
		pairId = "TRAIT-053",
		name = "Mana-Starved (Greater)",
		tier = "common",
		effect = "Loses 10% MP for each remaining AP at end of turn.",
		category = "General",
	},
	["TRAIT-F-054"] = {
		kind = "flaw",
		pairId = "TRAIT-054",
		name = "Bazooka Klutz",
		tier = "common",
		effect = "When wielding a Bazooka: weapon base damage -25% and weapon WT +25%.",
		category = "Weapon Mastery",
	},
	["TRAIT-F-055"] = {
		kind = "flaw",
		pairId = "TRAIT-055",
		name = "Cursed Wounds (Greater)",
		tier = "uncommon",
		effect = "Healing received -35%",
		category = "Support",
	},
	["TRAIT-F-056"] = {
		kind = "flaw",
		pairId = "TRAIT-056",
		name = "Blowgun Klutz",
		tier = "common",
		effect = "When wielding a Blowgun: weapon base damage -25% and weapon WT +25%.",
		category = "Weapon Mastery",
	},
	["TRAIT-F-057"] = {
		kind = "flaw",
		pairId = "TRAIT-057",
		name = "Weak (Greater)",
		tier = "uncommon",
		effect = "STR -18%",
		category = "General",
	},
	["TRAIT-F-058"] = {
		kind = "flaw",
		pairId = "TRAIT-058",
		name = "Dim (Greater)",
		tier = "uncommon",
		effect = "INT -18%",
		category = "General",
	},
	["TRAIT-F-059"] = {
		kind = "flaw",
		pairId = "TRAIT-059",
		name = "Underdog (Greater)",
		tier = "uncommon",
		effect = "Damage inflicted to lower level targets -12%",
		category = "General",
	},
	["TRAIT-F-060"] = {
		kind = "flaw",
		pairId = "TRAIT-060",
		name = "Slow Channeler",
		tier = "uncommon",
		effect = "Skills Channel time increased by 25% RT",
		category = "General",
	},
	["TRAIT-F-061"] = {
		kind = "flaw",
		pairId = "TRAIT-061",
		name = "Jinxed (Greater)",
		tier = "uncommon",
		effect = "LUK -18%",
		category = "General",
	},
	["TRAIT-F-062"] = {
		kind = "flaw",
		pairId = "TRAIT-062",
		name = "Claws Klutz",
		tier = "common",
		effect = "When wielding a Claws: weapon base damage -25% and weapon WT +25%.",
		category = "Weapon Mastery",
	},
	["TRAIT-F-063"] = {
		kind = "flaw",
		pairId = "TRAIT-063",
		name = "Sloppy Fighter",
		tier = "uncommon",
		effect = "Melee attacks: Hit Quality -0.05",
		category = "General",
	},
	["TRAIT-F-064"] = {
		kind = "flaw",
		pairId = "TRAIT-064",
		name = "Muddled",
		tier = "uncommon",
		effect = "INT -10%, DEX -10%",
		category = "General",
	},
	["TRAIT-F-065"] = {
		kind = "flaw",
		pairId = "TRAIT-065",
		name = "Club Klutz",
		tier = "common",
		effect = "When wielding a Club: weapon base damage -25% and weapon WT +25%.",
		category = "Weapon Mastery",
	},
	["TRAIT-F-066"] = {
		kind = "flaw",
		pairId = "TRAIT-066",
		name = "Crossbow Klutz",
		tier = "common",
		effect = "When wielding a Crossbow: weapon base damage -25% and weapon WT +25%.",
		category = "Weapon Mastery",
	},
	["TRAIT-F-067"] = {
		kind = "flaw",
		pairId = "TRAIT-067",
		name = "Claustrophobic (Greater)",
		tier = "uncommon",
		effect = "Damage inflicted -7% for each enemy within 2 range.",
		category = "Combat",
	},
	["TRAIT-F-068"] = {
		kind = "flaw",
		pairId = "TRAIT-068",
		name = "Dagger Klutz",
		tier = "common",
		effect = "When wielding a Dagger: weapon base damage -25% and weapon WT +25%.",
		category = "Weapon Mastery",
	},
	["TRAIT-F-069"] = {
		kind = "flaw",
		pairId = "TRAIT-069",
		name = "Dark Disharmony",
		tier = "uncommon",
		effect = "Deals 20% less damage when attacking with Dark-tagged attacks.",
		category = "Element",
	},
	["TRAIT-F-070"] = {
		kind = "flaw",
		pairId = "TRAIT-070",
		name = "Shallow Well (Greater)",
		tier = "uncommon",
		effect = "25% less max MP from INT",
		category = "Intellect",
	},
	["TRAIT-F-071"] = {
		kind = "flaw",
		pairId = "TRAIT-071",
		name = "Exposed Armor (Greater)",
		tier = "uncommon",
		effect = "Defense from armor decreased by 24%",
		category = "General",
	},
	["TRAIT-F-072"] = {
		kind = "flaw",
		pairId = "TRAIT-072",
		name = "Clumsy (Greater)",
		tier = "uncommon",
		effect = "DEX -18%",
		category = "General",
	},
	["TRAIT-F-073"] = {
		kind = "flaw",
		pairId = "TRAIT-073",
		name = "Spendthrift (Greater)",
		tier = "uncommon",
		effect = "Skill MP cost increased by 24%",
		category = "General",
	},
	["TRAIT-F-074"] = {
		kind = "flaw",
		pairId = "TRAIT-074",
		name = "Electric Disharmony",
		tier = "common",
		effect = "Deals 20% less damage when attacking with Electric-tagged attacks.",
		category = "Element",
	},
	["TRAIT-F-075"] = {
		kind = "flaw",
		pairId = "TRAIT-075",
		name = "Near-Sighted",
		tier = "uncommon",
		effect = "Discovery radius -1",
		category = "General",
	},
	["TRAIT-F-076"] = {
		kind = "flaw",
		pairId = "TRAIT-076",
		name = "Slow Learner (Greater)",
		tier = "uncommon",
		effect = "Gains 15% less XP from battles than normal.",
		category = "General",
	},
	["TRAIT-F-077"] = {
		kind = "flaw",
		pairId = "TRAIT-077",
		name = "Fire Disharmony",
		tier = "common",
		effect = "Deals 20% less damage when attacking with Fire-tagged attacks.",
		category = "Element",
	},
	["TRAIT-F-078"] = {
		kind = "flaw",
		pairId = "TRAIT-078",
		name = "Flammable (Greater)",
		tier = "common",
		effect = "Burn damage received +60%.",
		category = "Endurance",
	},
	["TRAIT-F-079"] = {
		kind = "flaw",
		pairId = "TRAIT-079",
		name = "Laggy Caster",
		tier = "uncommon",
		effect = "Skill delay time increased by 25% RT",
		category = "General",
	},
	["TRAIT-F-080"] = {
		kind = "flaw",
		pairId = "TRAIT-080",
		name = "Plodding",
		tier = "uncommon",
		effect = "Movement RT cost increased by 25%, subtracted from AGI bonus.",
		category = "Agility",
	},
	["TRAIT-F-081"] = {
		kind = "flaw",
		pairId = "TRAIT-081",
		name = "Distracted",
		tier = "uncommon",
		effect = "DEX -10%, INT -10%",
		category = "General",
	},
	["TRAIT-F-082"] = {
		kind = "flaw",
		pairId = "TRAIT-082",
		name = "Great Bow Klutz",
		tier = "common",
		effect = "When wielding a Great Bow: weapon base damage -25% and weapon WT +25%.",
		category = "Weapon Mastery",
	},
	["TRAIT-F-083"] = {
		kind = "flaw",
		pairId = "TRAIT-083",
		name = "Greatsword Klutz",
		tier = "common",
		effect = "When wielding a Greatsword: weapon base damage -25% and weapon WT +25%.",
		category = "Weapon Mastery",
	},
	["TRAIT-F-084"] = {
		kind = "flaw",
		pairId = "TRAIT-084",
		name = "Hammer Klutz",
		tier = "common",
		effect = "When wielding a Hammer: weapon base damage -25% and weapon WT +25%.",
		category = "Weapon Mastery",
	},
	["TRAIT-F-085"] = {
		kind = "flaw",
		pairId = "TRAIT-085",
		name = "Sickly (Greater)",
		tier = "uncommon",
		effect = "VIT -18%",
		category = "General",
	},
	["TRAIT-F-086"] = {
		kind = "flaw",
		pairId = "TRAIT-086",
		name = "Feather Strikes (Greater)",
		tier = "uncommon",
		effect = "25% of weapon WT is subtracted from base weapon damage",
		category = "Combat",
	},
	["TRAIT-F-087"] = {
		kind = "flaw",
		pairId = "TRAIT-087",
		name = "Downhill Struggle",
		tier = "uncommon",
		effect = "when attack target is at lower elevation, -5% damage per elevation difference",
		category = "Tactical",
	},
	["TRAIT-F-088"] = {
		kind = "flaw",
		pairId = "TRAIT-088",
		name = "Stubby Legs (Greater)",
		tier = "uncommon",
		effect = "-2 Jump",
		category = "Precision",
	},
	["TRAIT-F-089"] = {
		kind = "flaw",
		pairId = "TRAIT-089",
		name = "Holy Disharmony",
		tier = "common",
		effect = "Deals 20% less damage when attacking with Holy-tagged attacks.",
		category = "Element",
	},
	["TRAIT-F-090"] = {
		kind = "flaw",
		pairId = "TRAIT-090",
		name = "Ice Disharmony",
		tier = "common",
		effect = "Deals 20% less damage when attacking with Ice-tagged attacks.",
		category = "Element",
	},
	["TRAIT-F-091"] = {
		kind = "flaw",
		pairId = "TRAIT-091",
		name = "Weak Stomach (Greater)",
		tier = "common",
		effect = "Poison damage received +60%.",
		category = "Endurance",
	},
	["TRAIT-F-092"] = {
		kind = "flaw",
		pairId = "TRAIT-092",
		name = "Brittle Plating (Greater)",
		tier = "uncommon",
		effect = "25% of total non-weapon WT is subtracted from base armor",
		category = "Endurance",
	},
	["TRAIT-F-093"] = {
		kind = "flaw",
		pairId = "TRAIT-093",
		name = "Item Fumbler (Greater)",
		tier = "uncommon",
		effect = "Healing and Damaging items effect are reduced by 30%",
		category = "General",
	},
	["TRAIT-F-094"] = {
		kind = "flaw",
		pairId = "TRAIT-094",
		name = "Clumsy (Greater)",
		tier = "uncommon",
		effect = "Precision -15%",
		category = "General",
	},
	["TRAIT-F-095"] = {
		kind = "flaw",
		pairId = "TRAIT-095",
		name = "Heavy-Footed",
		tier = "uncommon",
		effect = "evasiveness - 10%",
		category = "General",
	},
	["TRAIT-F-096"] = {
		kind = "flaw",
		pairId = "TRAIT-096",
		name = "Short Reach",
		tier = "common",
		effect = "-1 interact range",
		category = "Utility",
	},
	["TRAIT-F-097"] = {
		kind = "flaw",
		pairId = "TRAIT-097",
		name = "Short Strider",
		tier = "common",
		effect = "-1 movement range.",
		category = "General",
	},
	["TRAIT-F-098"] = {
		kind = "flaw",
		pairId = "TRAIT-098",
		name = "Longbow Klutz",
		tier = "common",
		effect = "When wielding a Longbow: weapon base damage -25% and weapon WT +25%.",
		category = "Weapon Mastery",
	},
	["TRAIT-F-099"] = {
		kind = "flaw",
		pairId = "TRAIT-099",
		name = "Unlucky (Greater)",
		tier = "uncommon",
		effect = "15% fortune penalty",
		category = "General",
	},
	["TRAIT-F-100"] = {
		kind = "flaw",
		pairId = "TRAIT-100",
		name = "Doomed",
		tier = "uncommon",
		effect = "LUK -10%, VIT -10%",
		category = "General",
	},
	["TRAIT-F-101"] = {
		kind = "flaw",
		pairId = "TRAIT-101",
		name = "Skill Issues",
		tier = "uncommon",
		effect = "Summoned units have 10% fewer primary stats and deal 10% less damage.",
		category = "General",
	},
	["TRAIT-F-102"] = {
		kind = "flaw",
		pairId = "TRAIT-102",
		name = "Sluggish (Greater)",
		tier = "uncommon",
		effect = "AGI -18%",
		category = "General",
	},
	["TRAIT-F-103"] = {
		kind = "flaw",
		pairId = "TRAIT-103",
		name = "Merciful (Greater)",
		tier = "uncommon",
		effect = "Damage inflicted to targets suffering from debuff reduced by 12%",
		category = "General",
	},
	["TRAIT-F-104"] = {
		kind = "flaw",
		pairId = "TRAIT-104",
		name = "Pistol Klutz",
		tier = "common",
		effect = "When wielding a Pistol: weapon base damage -25% and weapon WT +25%.",
		category = "Weapon Mastery",
	},
	["TRAIT-F-105"] = {
		kind = "flaw",
		pairId = "TRAIT-105",
		name = "Frail Arms",
		tier = "common",
		effect = "-1 force",
		category = "Physical Prowess",
	},
	["TRAIT-F-106"] = {
		kind = "flaw",
		pairId = "TRAIT-106",
		name = "Humble",
		tier = "uncommon",
		effect = "Damage inflicted to higher level targets -10%",
		category = "General",
	},
	["TRAIT-F-107"] = {
		kind = "flaw",
		pairId = "TRAIT-107",
		name = "Buff-Blind",
		tier = "uncommon",
		effect = "Attacks grant one random buff to the target instead",
		category = "General",
	},
	["TRAIT-F-108"] = {
		kind = "flaw",
		pairId = "TRAIT-108",
		name = "Hemophiliac (Greater)",
		tier = "common",
		effect = "Bleed damage received +60%.",
		category = "Endurance",
	},
	["TRAIT-F-109"] = {
		kind = "flaw",
		pairId = "TRAIT-109",
		name = "Slow to Recover (Greater)",
		tier = "uncommon",
		effect = "Recovers with only 25% HP after battle; revive HP halved.",
		category = "General",
	},
	["TRAIT-F-110"] = {
		kind = "flaw",
		pairId = "TRAIT-110",
		name = "Toppling",
		tier = "common",
		effect = "-1 stability",
		category = "Endurance",
	},
	["TRAIT-F-111"] = {
		kind = "flaw",
		pairId = "TRAIT-111",
		name = "Pacifist",
		tier = "uncommon",
		effect = "Damage reduced by 5% for each enemy this unit has killed in current battle",
		category = "General",
	},
	["TRAIT-F-112"] = {
		kind = "flaw",
		pairId = "TRAIT-112",
		name = "Restless (Greater)",
		tier = "uncommon",
		effect = "-2 range if unit did not move in previous turn.",
		category = "Tactical",
	},
	["TRAIT-F-113"] = {
		kind = "flaw",
		pairId = "TRAIT-113",
		name = "Spear Klutz",
		tier = "common",
		effect = "When wielding a Spear: weapon base damage -25% and weapon WT +25%.",
		category = "Weapon Mastery",
	},
	["TRAIT-F-114"] = {
		kind = "flaw",
		pairId = "TRAIT-114",
		name = "Unstable Footing",
		tier = "uncommon",
		effect = "Landing on a tile without an effect causes a random tile effect.",
		category = "General",
	},
	["TRAIT-F-115"] = {
		kind = "flaw",
		pairId = "TRAIT-115",
		name = "Staff Klutz",
		tier = "common",
		effect = "When wielding a Staff: weapon base damage -25% and weapon WT +25%.",
		category = "Weapon Mastery",
	},
	["TRAIT-F-116"] = {
		kind = "flaw",
		pairId = "TRAIT-116",
		name = "Weakened Core",
		tier = "uncommon",
		effect = "VIT -10%, STR -10%",
		category = "General",
	},
	["TRAIT-F-117"] = {
		kind = "flaw",
		pairId = "TRAIT-117",
		name = "Shaky Aim",
		tier = "uncommon",
		effect = "Ranged attacks: Hit Quality -0.05",
		category = "General",
	},
	["TRAIT-F-118"] = {
		kind = "flaw",
		pairId = "TRAIT-118",
		name = "Weak Grip (Greater)",
		tier = "uncommon",
		effect = "Gear WT increased by 25%, subtracted from STR bonus",
		category = "General",
	},
	["TRAIT-F-119"] = {
		kind = "flaw",
		pairId = "TRAIT-119",
		name = "Sword Breaker Klutz",
		tier = "common",
		effect = "When wielding a Sword Breaker: weapon base damage -25% and weapon WT +25%.",
		category = "Weapon Mastery",
	},
	["TRAIT-F-120"] = {
		kind = "flaw",
		pairId = "TRAIT-120",
		name = "Sword Klutz",
		tier = "common",
		effect = "When wielding a Sword: weapon base damage -25% and weapon WT +25%.",
		category = "Weapon Mastery",
	},
	["TRAIT-F-121"] = {
		kind = "flaw",
		pairId = "TRAIT-121",
		name = "Thin Skin (Greater)",
		tier = "uncommon",
		effect = "Takes 15% more damage.",
		category = "General",
	},
	["TRAIT-F-122"] = {
		kind = "flaw",
		pairId = "TRAIT-122",
		name = "Spendthrift Looter",
		tier = "uncommon",
		effect = "Gain 50% less gold from treasure chests opened.",
		category = "General",
	},
	["TRAIT-F-123"] = {
		kind = "flaw",
		pairId = "TRAIT-123",
		name = "Wand Klutz",
		tier = "common",
		effect = "When wielding a Wand: weapon base damage -25% and weapon WT +25%.",
		category = "Weapon Mastery",
	},
	["TRAIT-F-124"] = {
		kind = "flaw",
		pairId = "TRAIT-124",
		name = "War Axe Klutz",
		tier = "common",
		effect = "When wielding a War Axe: weapon base damage -25% and weapon WT +25%.",
		category = "Weapon Mastery",
	},
	["TRAIT-F-125"] = {
		kind = "flaw",
		pairId = "TRAIT-125",
		name = "Water Disharmony",
		tier = "uncommon",
		effect = "Deals 20% less damage when attacking with Water-tagged attacks.",
		category = "Element",
	},
	["TRAIT-F-126"] = {
		kind = "flaw",
		pairId = "TRAIT-126",
		name = "Whip Klutz",
		tier = "common",
		effect = "When wielding a Whip: weapon base damage -25% and weapon WT +25%.",
		category = "Weapon Mastery",
	},
	["TRAIT-F-127"] = {
		kind = "flaw",
		pairId = "TRAIT-127",
		name = "Scrawny",
		tier = "uncommon",
		effect = "STR -10%, AGI -10%",
		category = "General",
	},
	["TRAIT-F-128"] = {
		kind = "flaw",
		pairId = "TRAIT-128",
		name = "Inept",
		tier = "rare",
		effect = "Skill damage -15%",
		category = "General",
	},
	["TRAIT-F-129"] = {
		kind = "flaw",
		pairId = "TRAIT-129",
		name = "Exposed to Range",
		tier = "rare",
		effect = "Damage received from enemies equipped with ranged weapons increased by 25%",
		category = "General",
	},
	["TRAIT-F-130"] = {
		kind = "flaw",
		pairId = "TRAIT-130",
		name = "Exposed (Greater)",
		tier = "rare",
		effect = "when attack target is at higher elevation, -11% damage per elevation difference",
		category = "General",
	},
	["TRAIT-F-131"] = {
		kind = "flaw",
		pairId = "TRAIT-131",
		name = "Hemophage",
		tier = "rare",
		effect = "Lose 15% of current HP each time an ally is KO'd nearby",
		category = "General",
	},
	["TRAIT-F-132"] = {
		kind = "flaw",
		pairId = "TRAIT-132",
		name = "Lingering Curse",
		tier = "rare",
		effect = "Being attacked applies 1 random debuff to self",
		category = "General",
	},
	["TRAIT-F-133"] = {
		kind = "flaw",
		pairId = "TRAIT-133",
		name = "Fragile to Blasts",
		tier = "rare",
		effect = "Receives 50% more damage from AOE attacks.",
		category = "Endurance",
	},
	["TRAIT-F-134"] = {
		kind = "flaw",
		pairId = "TRAIT-134",
		name = "Sitting Duck",
		tier = "rare",
		effect = "Until next Turn, gain -5% evasion per tile traveled (using skill or by move)",
		category = "General",
	},
	["TRAIT-F-135"] = {
		kind = "flaw",
		pairId = "TRAIT-135",
		name = "Near-Sighted (Greater)",
		tier = "rare",
		effect = "Discovery radius -1.2",
		category = "General",
	},
	["TRAIT-F-136"] = {
		kind = "flaw",
		pairId = "TRAIT-136",
		name = "Downhill Struggle (Greater)",
		tier = "rare",
		effect = "when attack target is at lower elevation, -7% damage per elevation difference",
		category = "Tactical",
	},
	["TRAIT-F-137"] = {
		kind = "flaw",
		pairId = "TRAIT-137",
		name = "Heavy-Footed (Greater)",
		tier = "rare",
		effect = "evasiveness - 12%",
		category = "General",
	},
	["TRAIT-F-138"] = {
		kind = "flaw",
		pairId = "TRAIT-138",
		name = "Short Reach (Greater)",
		tier = "rare",
		effect = "-2 interact range",
		category = "Utility",
	},
	["TRAIT-F-139"] = {
		kind = "flaw",
		pairId = "TRAIT-139",
		name = "Short Strider (Greater)",
		tier = "rare",
		effect = "-2 movement range.",
		category = "General",
	},
	["TRAIT-F-140"] = {
		kind = "flaw",
		pairId = "TRAIT-140",
		name = "Melee Clumsy",
		tier = "rare",
		effect = "Damage inflicted with melee weapon reduced by 15%, damage received from melee weapon increased by 15%",
		category = "General",
	},
	["TRAIT-F-141"] = {
		kind = "flaw",
		pairId = "TRAIT-141",
		name = "Skill Issues (Greater)",
		tier = "rare",
		effect = "Summoned units have 12% fewer primary stats and deal 10% less damage.",
		category = "General",
	},
	["TRAIT-F-142"] = {
		kind = "flaw",
		pairId = "TRAIT-142",
		name = "Bogged Down",
		tier = "rare",
		effect = "Terrain movement costs are increased by 50%.",
		category = "Utility",
	},
	["TRAIT-F-143"] = {
		kind = "flaw",
		pairId = "TRAIT-143",
		name = "Frail Arms (Greater)",
		tier = "rare",
		effect = "-2 force",
		category = "Physical Prowess",
	},
	["TRAIT-F-144"] = {
		kind = "flaw",
		pairId = "TRAIT-144",
		name = "Humble (Greater)",
		tier = "rare",
		effect = "Damage inflicted to higher level targets -12%",
		category = "General",
	},
	["TRAIT-F-145"] = {
		kind = "flaw",
		pairId = "TRAIT-145",
		name = "Defenseless",
		tier = "rare",
		effect = "When attacked, this unit is inflicted with a random debuff.",
		category = "Combat",
	},
	["TRAIT-F-146"] = {
		kind = "flaw",
		pairId = "TRAIT-146",
		name = "Toppling (Greater)",
		tier = "rare",
		effect = "-2 stability",
		category = "Endurance",
	},
	["TRAIT-F-147"] = {
		kind = "flaw",
		pairId = "TRAIT-147",
		name = "Pacifist (Greater)",
		tier = "rare",
		effect = "Damage reduced by 6% for each enemy this unit has killed in current battle",
		category = "General",
	},
	["TRAIT-F-148"] = {
		kind = "flaw",
		pairId = "TRAIT-148",
		name = "Mana Leak",
		tier = "rare",
		effect = "Lose 15% of current MP each time this unit KOs an enemy",
		category = "General",
	},
	["TRAIT-F-149"] = {
		kind = "flaw",
		pairId = "TRAIT-149",
		name = "Time Freed",
		tier = "rare",
		effect = "RT Delay caused reduced by 25%",
		category = "General",
	},
	["TRAIT-F-150"] = {
		kind = "flaw",
		pairId = "TRAIT-150",
		name = "Festering",
		tier = "rare",
		effect = "DOT damage received is doubled.",
		category = "Endurance",
	},
	["TRAIT-F-151"] = {
		kind = "flaw",
		pairId = "TRAIT-151",
		name = "Spendthrift Looter (Greater)",
		tier = "rare",
		effect = "Gain 60% less gold from treasure chests opened.",
		category = "General",
	},
	["TRAIT-F-152"] = {
		kind = "flaw",
		pairId = "TRAIT-152",
		name = "Meek",
		tier = "rare",
		effect = "Every time unit is attacked, receive a 5% damage penalty. Accumulates. Removed at end of next turn.",
		category = "General",
	},
	["TRAIT-F-153"] = {
		kind = "flaw",
		pairId = "TRAIT-153",
		name = "Inept (Greater)",
		tier = "epic",
		effect = "Skill damage -18%",
		category = "General",
	},
	["TRAIT-F-154"] = {
		kind = "flaw",
		pairId = "TRAIT-154",
		name = "Meek Blood",
		tier = "epic",
		effect = "While below 30% HP: Final damage dealt -20%",
		category = "General",
	},
	["TRAIT-F-155"] = {
		kind = "flaw",
		pairId = "TRAIT-155",
		name = "Bleed Phobia",
		tier = "epic",
		effect = "Cannot inflict or trigger bleed with attacks.",
		category = "General",
	},
	["TRAIT-F-156"] = {
		kind = "flaw",
		pairId = "TRAIT-156",
		name = "Hemophage (Greater)",
		tier = "epic",
		effect = "Lose 18% of current HP each time an ally is KO'd nearby",
		category = "General",
	},
	["TRAIT-F-157"] = {
		kind = "flaw",
		pairId = "TRAIT-157",
		name = "Burn Phobia",
		tier = "epic",
		effect = "Cannot trigger accumulated burn damage with attacks. Burn inflicted -5% of base damage.",
		category = "General",
	},
	["TRAIT-F-158"] = {
		kind = "flaw",
		pairId = "TRAIT-158",
		name = "Coward",
		tier = "epic",
		effect = "While below 30% HP: Defense -30%",
		category = "General",
	},
	["TRAIT-F-159"] = {
		kind = "flaw",
		pairId = "TRAIT-159",
		name = "Guard Klutz",
		tier = "epic",
		effect = "Damage Reduction from guard -10%",
		category = "General",
	},
	["TRAIT-F-160"] = {
		kind = "flaw",
		pairId = "TRAIT-160",
		name = "Lifeless",
		tier = "epic",
		effect = "Recoil: after dealing direct damage, this unit takes self-damage equal to 4% of the direct damage dealt (half of Lifesteal's 8%). Non-lethal: recoil can never reduce HP below 1.",
		category = "General",
	},
	["TRAIT-F-161"] = {
		kind = "flaw",
		pairId = "TRAIT-161",
		name = "Melee Clumsy (Greater)",
		tier = "epic",
		effect = "Damage inflicted with melee weapon reduced by 18%, damage received from melee weapon increased by 15%",
		category = "General",
	},
	["TRAIT-F-162"] = {
		kind = "flaw",
		pairId = "TRAIT-162",
		name = "Sluggish Finisher",
		tier = "epic",
		effect = "Once per turn, lose 1 AP when an ally is KO'd",
		category = "General",
	},
	["TRAIT-F-163"] = {
		kind = "flaw",
		pairId = "TRAIT-163",
		name = "Poison Phobia",
		tier = "epic",
		effect = "Cannot inflict or trigger poison with attacks.",
		category = "General",
	},
	["TRAIT-F-164"] = {
		kind = "flaw",
		pairId = "TRAIT-164",
		name = "Sluggish",
		tier = "epic",
		effect = "10% higher base RT",
		category = "General",
	},
	["TRAIT-F-165"] = {
		kind = "flaw",
		pairId = "TRAIT-165",
		name = "Mana Leak (Greater)",
		tier = "epic",
		effect = "Lose 18% of current MP each time this unit KOs an enemy",
		category = "General",
	},
	["TRAIT-F-166"] = {
		kind = "flaw",
		pairId = "TRAIT-166",
		name = "Venom Phobia",
		tier = "epic",
		effect = "Cannot inflict or trigger venom with attacks.",
		category = "General",
	},
	["TRAIT-F-167"] = {
		kind = "flaw",
		pairId = "TRAIT-167",
		name = "Meek (Greater)",
		tier = "epic",
		effect = "Every time unit is attacked, receive a 6% damage penalty. Accumulates. Removed at end of next turn.",
		category = "General",
	},
	["TRAIT-F-168"] = {
		kind = "flaw",
		pairId = "TRAIT-168",
		name = "Arcane Prodigy (flaw)",
		tier = "legendary",
		effect = "Skill Potency -12%, Skill RT Cost +8%",
		category = "General",
	},
	["TRAIT-F-169"] = {
		kind = "flaw",
		pairId = "TRAIT-169",
		name = "Meek Blood (Greater)",
		tier = "legendary",
		effect = "While below 36% HP: Final damage dealt -20%",
		category = "General",
	},
	["TRAIT-F-170"] = {
		kind = "flaw",
		pairId = "TRAIT-170",
		name = "Coward (Greater)",
		tier = "legendary",
		effect = "While below 36% HP: Defense -30%",
		category = "General",
	},
	["TRAIT-F-171"] = {
		kind = "flaw",
		pairId = "TRAIT-171",
		name = "Dual Strike (flaw)",
		tier = "legendary",
		effect = "Basic Attack costs double RT.",
		category = "General",
	},
	["TRAIT-F-172"] = {
		kind = "flaw",
		pairId = "TRAIT-172",
		name = "Elemental Mastery (flaw)",
		tier = "legendary",
		effect = "All elemental damage received +20%",
		category = "General",
	},
	["TRAIT-F-173"] = {
		kind = "flaw",
		pairId = "TRAIT-173",
		name = "Guard Klutz (Greater)",
		tier = "legendary",
		effect = "Damage Reduction from guard -12%",
		category = "General",
	},
	["TRAIT-F-174"] = {
		kind = "flaw",
		pairId = "TRAIT-174",
		name = "Lifeless (Greater)",
		tier = "legendary",
		effect = "Recoil: after dealing direct damage, this unit takes self-damage equal to 4.8% of the direct damage dealt (half of Greater Lifesteal's 9.6%). Non-lethal: recoil can never reduce HP below 1.",
		category = "General",
	},
	["TRAIT-F-175"] = {
		kind = "flaw",
		pairId = "TRAIT-175",
		name = "Martial Footwork (flaw)",
		tier = "legendary",
		effect = "If first action each turn is Move, the turn ends immediately after moving.",
		category = "General",
	},
	["TRAIT-F-176"] = {
		kind = "flaw",
		pairId = "TRAIT-176",
		name = "Overwhelming Force (flaw)",
		tier = "legendary",
		effect = "Force -3",
		category = "General",
	},
	["TRAIT-F-177"] = {
		kind = "flaw",
		pairId = "TRAIT-177",
		name = "Soul Harvest (flaw)",
		tier = "legendary",
		effect = "After 3000 CT in battle: all primary stats -8% for rest of battle",
		category = "General",
	},
	["TRAIT-F-178"] = {
		kind = "flaw",
		pairId = "TRAIT-178",
		name = "Temporal Drag",
		tier = "legendary",
		effect = "Base RT +8%, Starting RT +15%",
		category = "General",
	},
	["TRAIT-F-179"] = {
		kind = "flaw",
		pairId = "TRAIT-179",
		name = "Undying Will (flaw)",
		tier = "legendary",
		effect = "Revives with only 1 HP.",
		category = "General",
	},
	["TRAIT-P-001"] = {
		kind = "perk",
		pairId = "TRAIT-001",
		name = "Accessory Specialist",
		tier = "common",
		effect = "Double the numerical Base and Bonus stats from Accessory armor (Passive effects excluded).",
		category = "Armor Mastery",
	},
	["TRAIT-P-002"] = {
		kind = "perk",
		pairId = "TRAIT-002",
		name = "Adrenaline",
		tier = "common",
		effect = "Deals 15% more damage while below half HP.",
		category = "General",
	},
	["TRAIT-P-003"] = {
		kind = "perk",
		pairId = "TRAIT-003",
		name = "Antivenom Blood",
		tier = "common",
		effect = "Venom damage received -50%.",
		category = "Endurance",
	},
	["TRAIT-P-004"] = {
		kind = "perk",
		pairId = "TRAIT-004",
		name = "Backstabber",
		tier = "common",
		effect = "15% Bonus damage when attacking from the side or behind (backstab synergy).",
		category = "General",
	},
	["TRAIT-P-005"] = {
		kind = "perk",
		pairId = "TRAIT-005",
		name = "Basics",
		tier = "common",
		effect = "Basic Attack use only 60% of weapon WT. Does not affect skills",
		category = "General",
	},
	["TRAIT-P-006"] = {
		kind = "perk",
		pairId = "TRAIT-006",
		name = "Battle Focus",
		tier = "common",
		effect = "Recovers 5% MP for each remaining AP at end of turn.",
		category = "General",
	},
	["TRAIT-P-007"] = {
		kind = "perk",
		pairId = "TRAIT-007",
		name = "Blessed Recovery",
		tier = "common",
		effect = "healing received +25%",
		category = "Support",
	},
	["TRAIT-P-008"] = {
		kind = "perk",
		pairId = "TRAIT-008",
		name = "Body Specialist",
		tier = "common",
		effect = "Double the numerical Base and Bonus stats from Body armor (Passive effects excluded).",
		category = "Armor Mastery",
	},
	["TRAIT-P-009"] = {
		kind = "perk",
		pairId = "TRAIT-009",
		name = "Brawny",
		tier = "common",
		effect = "STR +15%",
		category = "General",
	},
	["TRAIT-P-010"] = {
		kind = "perk",
		pairId = "TRAIT-010",
		name = "Bright",
		tier = "common",
		effect = "INT +15%",
		category = "General",
	},
	["TRAIT-P-011"] = {
		kind = "perk",
		pairId = "TRAIT-011",
		name = "Bully",
		tier = "common",
		effect = "Damage inflicted to lower level targets +10%",
		category = "General",
	},
	["TRAIT-P-012"] = {
		kind = "perk",
		pairId = "TRAIT-012",
		name = "Charmed",
		tier = "common",
		effect = "LUK +15%",
		category = "General",
	},
	["TRAIT-P-013"] = {
		kind = "perk",
		pairId = "TRAIT-013",
		name = "Crowd Fighter",
		tier = "common",
		effect = "damage inflicted +5% for each enemy within 2 range",
		category = "Combat",
	},
	["TRAIT-P-014"] = {
		kind = "perk",
		pairId = "TRAIT-014",
		name = "Dark Affinity",
		tier = "common",
		effect = "Takes 50% reduced damage from Dark-tagged attacks.",
		category = "Element",
	},
	["TRAIT-P-015"] = {
		kind = "perk",
		pairId = "TRAIT-015",
		name = "Deep Well",
		tier = "common",
		effect = "20% more max MP from INT",
		category = "Intellect",
	},
	["TRAIT-P-016"] = {
		kind = "perk",
		pairId = "TRAIT-016",
		name = "Defensive",
		tier = "common",
		effect = "Defense from armor increased by 20%",
		category = "General",
	},
	["TRAIT-P-017"] = {
		kind = "perk",
		pairId = "TRAIT-017",
		name = "Deft",
		tier = "common",
		effect = "DEX +15%",
		category = "General",
	},
	["TRAIT-P-018"] = {
		kind = "perk",
		pairId = "TRAIT-018",
		name = "Economist",
		tier = "common",
		effect = "Skill MP cost is reduced by 20%",
		category = "General",
	},
	["TRAIT-P-019"] = {
		kind = "perk",
		pairId = "TRAIT-019",
		name = "Electric Affinity",
		tier = "common",
		effect = "Takes 50% reduced damage from Electric-tagged attacks.",
		category = "Element",
	},
	["TRAIT-P-020"] = {
		kind = "perk",
		pairId = "TRAIT-020",
		name = "Fast Learner",
		tier = "common",
		effect = "Gains more 10% XP from battles than normal.",
		category = "General",
	},
	["TRAIT-P-021"] = {
		kind = "perk",
		pairId = "TRAIT-021",
		name = "Feet Specialist",
		tier = "common",
		effect = "Double the numerical Base and Bonus stats from Feet armor (Passive effects excluded).",
		category = "Armor Mastery",
	},
	["TRAIT-P-022"] = {
		kind = "perk",
		pairId = "TRAIT-022",
		name = "Fire Affinity",
		tier = "common",
		effect = "Takes 50% reduced damage from Fire-tagged attacks.",
		category = "Element",
	},
	["TRAIT-P-023"] = {
		kind = "perk",
		pairId = "TRAIT-023",
		name = "Fire-Hardened",
		tier = "common",
		effect = "Burn damage received -50%.",
		category = "Endurance",
	},
	["TRAIT-P-024"] = {
		kind = "perk",
		pairId = "TRAIT-024",
		name = "Gloves Specialist",
		tier = "common",
		effect = "Double the numerical Base and Bonus stats from Gloves armor (Passive effects excluded).",
		category = "Armor Mastery",
	},
	["TRAIT-P-025"] = {
		kind = "perk",
		pairId = "TRAIT-025",
		name = "Hardy",
		tier = "common",
		effect = "20% more max HP from VIT",
		category = "General",
	},
	["TRAIT-P-026"] = {
		kind = "perk",
		pairId = "TRAIT-026",
		name = "Head Specialist",
		tier = "common",
		effect = "Double the numerical Base and Bonus stats from Head armor (Passive effects excluded).",
		category = "Armor Mastery",
	},
	["TRAIT-P-027"] = {
		kind = "perk",
		pairId = "TRAIT-027",
		name = "Hearty",
		tier = "common",
		effect = "VIT +15%",
		category = "General",
	},
	["TRAIT-P-028"] = {
		kind = "perk",
		pairId = "TRAIT-028",
		name = "Heavy Hitter",
		tier = "common",
		effect = "20% of weapon WT is added as base weapon damage",
		category = "Combat",
	},
	["TRAIT-P-029"] = {
		kind = "perk",
		pairId = "TRAIT-029",
		name = "High Jumper",
		tier = "common",
		effect = "+1 Jump",
		category = "Precision",
	},
	["TRAIT-P-030"] = {
		kind = "perk",
		pairId = "TRAIT-030",
		name = "Holy Affinity",
		tier = "common",
		effect = "Takes 50% reduced damage from Holy-tagged attacks.",
		category = "Element",
	},
	["TRAIT-P-031"] = {
		kind = "perk",
		pairId = "TRAIT-031",
		name = "Ice Affinity",
		tier = "common",
		effect = "Takes 50% reduced damage from Ice-tagged attacks.",
		category = "Element",
	},
	["TRAIT-P-032"] = {
		kind = "perk",
		pairId = "TRAIT-032",
		name = "Iron Stomach",
		tier = "common",
		effect = "Poison damage received -50%.",
		category = "Endurance",
	},
	["TRAIT-P-033"] = {
		kind = "perk",
		pairId = "TRAIT-033",
		name = "Iron Will",
		tier = "common",
		effect = "Debuffs and negative status effects duration reduced by 1 turn or 400 CT depending on duration basis.",
		category = "General",
	},
	["TRAIT-P-034"] = {
		kind = "perk",
		pairId = "TRAIT-034",
		name = "Ironhide",
		tier = "common",
		effect = "20% of total non-weapon WT is added as base armor",
		category = "Endurance",
	},
	["TRAIT-P-035"] = {
		kind = "perk",
		pairId = "TRAIT-035",
		name = "Item Specialist",
		tier = "common",
		effect = "Healing and Damaging items effect are increased by 25%",
		category = "General",
	},
	["TRAIT-P-036"] = {
		kind = "perk",
		pairId = "TRAIT-036",
		name = "Keen Aim",
		tier = "common",
		effect = "Precision +10%",
		category = "General",
	},
	["TRAIT-P-037"] = {
		kind = "perk",
		pairId = "TRAIT-037",
		name = "Lucky",
		tier = "common",
		effect = "10% fortune bonus",
		category = "General",
	},
	["TRAIT-P-038"] = {
		kind = "perk",
		pairId = "TRAIT-038",
		name = "Nimble",
		tier = "common",
		effect = "AGI +15%",
		category = "General",
	},
	["TRAIT-P-039"] = {
		kind = "perk",
		pairId = "TRAIT-039",
		name = "Opportunist",
		tier = "common",
		effect = "Damage inflicted to targets suffering from debuff increased by 10%",
		category = "General",
	},
	["TRAIT-P-040"] = {
		kind = "perk",
		pairId = "TRAIT-040",
		name = "Quick Clotting",
		tier = "common",
		effect = "Bleed damage received -50%.",
		category = "Endurance",
	},
	["TRAIT-P-041"] = {
		kind = "perk",
		pairId = "TRAIT-041",
		name = "Resilient",
		tier = "common",
		effect = "Recovers with 20% HP after battle or +20% of max hp when being revived.",
		category = "General",
	},
	["TRAIT-P-042"] = {
		kind = "perk",
		pairId = "TRAIT-042",
		name = "Sniper's Perch",
		tier = "common",
		effect = "+1 range if unit did not move in previous turn.",
		category = "Tactical",
	},
	["TRAIT-P-043"] = {
		kind = "perk",
		pairId = "TRAIT-043",
		name = "Strong Back",
		tier = "common",
		effect = "Gear WT reduced by 20% added to STR bonus",
		category = "General",
	},
	["TRAIT-P-044"] = {
		kind = "perk",
		pairId = "TRAIT-044",
		name = "Sure-Footed",
		tier = "common",
		effect = "Base Fall Damage received reduced by half before VIT bonus",
		category = "General",
	},
	["TRAIT-P-045"] = {
		kind = "perk",
		pairId = "TRAIT-045",
		name = "Thorny",
		tier = "common",
		effect = "Receive no collision damage. Units colliding with this unit take double collision damage.",
		category = "General",
	},
	["TRAIT-P-046"] = {
		kind = "perk",
		pairId = "TRAIT-046",
		name = "Tough Skin",
		tier = "common",
		effect = "Takes 10% less damage.",
		category = "General",
	},
	["TRAIT-P-047"] = {
		kind = "perk",
		pairId = "TRAIT-047",
		name = "Water Affinity",
		tier = "common",
		effect = "Takes 50% reduced damage from Water-tagged attacks.",
		category = "Element",
	},
	["TRAIT-P-048"] = {
		kind = "perk",
		pairId = "TRAIT-048",
		name = "Adrenaline (Greater)",
		tier = "uncommon",
		effect = "Deals 20% more damage while below half HP.",
		category = "General",
	},
	["TRAIT-P-049"] = {
		kind = "perk",
		pairId = "TRAIT-049",
		name = "Alert",
		tier = "uncommon",
		effect = "AGI +10%, LUK +10%",
		category = "General",
	},
	["TRAIT-P-050"] = {
		kind = "perk",
		pairId = "TRAIT-050",
		name = "Ambusher",
		tier = "uncommon",
		effect = "when attack target is at higher elevation, +8% damage per elevation difference",
		category = "General",
	},
	["TRAIT-P-051"] = {
		kind = "perk",
		pairId = "TRAIT-051",
		name = "Antivenom Blood (Greater)",
		tier = "common",
		effect = "Venom damage received -60%.",
		category = "Endurance",
	},
	["TRAIT-P-052"] = {
		kind = "perk",
		pairId = "TRAIT-052",
		name = "Backstabber (Greater)",
		tier = "common",
		effect = "20% Bonus damage when attacking from the side or behind (backstab synergy).",
		category = "General",
	},
	["TRAIT-P-053"] = {
		kind = "perk",
		pairId = "TRAIT-053",
		name = "Battle Focus (Greater)",
		tier = "common",
		effect = "Recovers 10% MP for each remaining AP at end of turn.",
		category = "General",
	},
	["TRAIT-P-054"] = {
		kind = "perk",
		pairId = "TRAIT-054",
		name = "Bazooka Specialist",
		tier = "common",
		effect = "When wielding a Bazooka: weapon base damage +25% and weapon WT -25%.",
		category = "Weapon Mastery",
	},
	["TRAIT-P-055"] = {
		kind = "perk",
		pairId = "TRAIT-055",
		name = "Blessed Recovery (Greater)",
		tier = "uncommon",
		effect = "healing received +35%",
		category = "Support",
	},
	["TRAIT-P-056"] = {
		kind = "perk",
		pairId = "TRAIT-056",
		name = "Blowgun Specialist",
		tier = "common",
		effect = "When wielding a Blowgun: weapon base damage +25% and weapon WT -25%.",
		category = "Weapon Mastery",
	},
	["TRAIT-P-057"] = {
		kind = "perk",
		pairId = "TRAIT-057",
		name = "Brawny (Greater)",
		tier = "uncommon",
		effect = "STR +18%",
		category = "General",
	},
	["TRAIT-P-058"] = {
		kind = "perk",
		pairId = "TRAIT-058",
		name = "Bright (Greater)",
		tier = "uncommon",
		effect = "INT +18%",
		category = "General",
	},
	["TRAIT-P-059"] = {
		kind = "perk",
		pairId = "TRAIT-059",
		name = "Bully (Greater)",
		tier = "uncommon",
		effect = "Damage inflicted to lower level targets +12%",
		category = "General",
	},
	["TRAIT-P-060"] = {
		kind = "perk",
		pairId = "TRAIT-060",
		name = "Channeler",
		tier = "uncommon",
		effect = "Skills Channel time reduced by 25% RT",
		category = "General",
	},
	["TRAIT-P-061"] = {
		kind = "perk",
		pairId = "TRAIT-061",
		name = "Charmed (Greater)",
		tier = "uncommon",
		effect = "LUK +18%",
		category = "General",
	},
	["TRAIT-P-062"] = {
		kind = "perk",
		pairId = "TRAIT-062",
		name = "Claws Specialist",
		tier = "common",
		effect = "When wielding a Claws: weapon base damage +25% and weapon WT -25%.",
		category = "Weapon Mastery",
	},
	["TRAIT-P-063"] = {
		kind = "perk",
		pairId = "TRAIT-063",
		name = "Clean Fighter",
		tier = "uncommon",
		effect = "Melee attacks: Hit Quality +0.05",
		category = "General",
	},
	["TRAIT-P-064"] = {
		kind = "perk",
		pairId = "TRAIT-064",
		name = "Clever",
		tier = "uncommon",
		effect = "INT +10%, DEX +10%",
		category = "General",
	},
	["TRAIT-P-065"] = {
		kind = "perk",
		pairId = "TRAIT-065",
		name = "Club Specialist",
		tier = "common",
		effect = "When wielding a Club: weapon base damage +25% and weapon WT -25%.",
		category = "Weapon Mastery",
	},
	["TRAIT-P-066"] = {
		kind = "perk",
		pairId = "TRAIT-066",
		name = "Crossbow Specialist",
		tier = "common",
		effect = "When wielding a Crossbow: weapon base damage +25% and weapon WT -25%.",
		category = "Weapon Mastery",
	},
	["TRAIT-P-067"] = {
		kind = "perk",
		pairId = "TRAIT-067",
		name = "Crowd Fighter (Greater)",
		tier = "uncommon",
		effect = "damage inflicted +7% for each enemy within 2 range",
		category = "Combat",
	},
	["TRAIT-P-068"] = {
		kind = "perk",
		pairId = "TRAIT-068",
		name = "Dagger Specialist",
		tier = "common",
		effect = "When wielding a Dagger: weapon base damage +25% and weapon WT -25%.",
		category = "Weapon Mastery",
	},
	["TRAIT-P-069"] = {
		kind = "perk",
		pairId = "TRAIT-069",
		name = "Dark Attunement",
		tier = "uncommon",
		effect = "Deals 20% more damage when attacking with Dark-tagged attacks.",
		category = "Element",
	},
	["TRAIT-P-070"] = {
		kind = "perk",
		pairId = "TRAIT-070",
		name = "Deep Well (Greater)",
		tier = "uncommon",
		effect = "25% more max MP from INT",
		category = "Intellect",
	},
	["TRAIT-P-071"] = {
		kind = "perk",
		pairId = "TRAIT-071",
		name = "Defensive (Greater)",
		tier = "uncommon",
		effect = "Defense from armor increased by 24%",
		category = "General",
	},
	["TRAIT-P-072"] = {
		kind = "perk",
		pairId = "TRAIT-072",
		name = "Deft (Greater)",
		tier = "uncommon",
		effect = "DEX +18%",
		category = "General",
	},
	["TRAIT-P-073"] = {
		kind = "perk",
		pairId = "TRAIT-073",
		name = "Economist (Greater)",
		tier = "uncommon",
		effect = "Skill MP cost is reduced by 24%",
		category = "General",
	},
	["TRAIT-P-074"] = {
		kind = "perk",
		pairId = "TRAIT-074",
		name = "Electric Attunement",
		tier = "common",
		effect = "Deals 20% more damage when attacking with Electric-tagged attacks.",
		category = "Element",
	},
	["TRAIT-P-075"] = {
		kind = "perk",
		pairId = "TRAIT-075",
		name = "Far-Sighted",
		tier = "uncommon",
		effect = "Discovery radius +1",
		category = "General",
	},
	["TRAIT-P-076"] = {
		kind = "perk",
		pairId = "TRAIT-076",
		name = "Fast Learner (Greater)",
		tier = "uncommon",
		effect = "Gains more 15% XP from battles than normal.",
		category = "General",
	},
	["TRAIT-P-077"] = {
		kind = "perk",
		pairId = "TRAIT-077",
		name = "Fire Attunement",
		tier = "common",
		effect = "Deals 20% more damage when attacking with Fire-tagged attacks.",
		category = "Element",
	},
	["TRAIT-P-078"] = {
		kind = "perk",
		pairId = "TRAIT-078",
		name = "Fire-Hardened (Greater)",
		tier = "common",
		effect = "Burn damage received -60%.",
		category = "Endurance",
	},
	["TRAIT-P-079"] = {
		kind = "perk",
		pairId = "TRAIT-079",
		name = "Flash-Caster",
		tier = "uncommon",
		effect = "Skill delay time reduced by 25% RT",
		category = "General",
	},
	["TRAIT-P-080"] = {
		kind = "perk",
		pairId = "TRAIT-080",
		name = "Fleet Runner",
		tier = "uncommon",
		effect = "movement RT cost reduced by 25% additive to Agi bonus",
		category = "Agility",
	},
	["TRAIT-P-081"] = {
		kind = "perk",
		pairId = "TRAIT-081",
		name = "Focused",
		tier = "uncommon",
		effect = "DEX +10%, INT +10%",
		category = "General",
	},
	["TRAIT-P-082"] = {
		kind = "perk",
		pairId = "TRAIT-082",
		name = "Great Bow Specialist",
		tier = "common",
		effect = "When wielding a Great Bow: weapon base damage +25% and weapon WT -25%.",
		category = "Weapon Mastery",
	},
	["TRAIT-P-083"] = {
		kind = "perk",
		pairId = "TRAIT-083",
		name = "Greatsword Specialist",
		tier = "common",
		effect = "When wielding a Greatsword: weapon base damage +25% and weapon WT -25%.",
		category = "Weapon Mastery",
	},
	["TRAIT-P-084"] = {
		kind = "perk",
		pairId = "TRAIT-084",
		name = "Hammer Specialist",
		tier = "common",
		effect = "When wielding a Hammer: weapon base damage +25% and weapon WT -25%.",
		category = "Weapon Mastery",
	},
	["TRAIT-P-085"] = {
		kind = "perk",
		pairId = "TRAIT-085",
		name = "Hearty (Greater)",
		tier = "uncommon",
		effect = "VIT +18%",
		category = "General",
	},
	["TRAIT-P-086"] = {
		kind = "perk",
		pairId = "TRAIT-086",
		name = "Heavy Hitter (Greater)",
		tier = "uncommon",
		effect = "25% of weapon WT is added as base weapon damage",
		category = "Combat",
	},
	["TRAIT-P-087"] = {
		kind = "perk",
		pairId = "TRAIT-087",
		name = "High Ground",
		tier = "uncommon",
		effect = "when attack target is at lower elevation, +5% damage per elevation difference",
		category = "Tactical",
	},
	["TRAIT-P-088"] = {
		kind = "perk",
		pairId = "TRAIT-088",
		name = "High Jumper (Greater)",
		tier = "uncommon",
		effect = "+2 Jump",
		category = "Precision",
	},
	["TRAIT-P-089"] = {
		kind = "perk",
		pairId = "TRAIT-089",
		name = "Holy Attunement",
		tier = "common",
		effect = "Deals 20% more damage when attacking with Holy-tagged attacks.",
		category = "Element",
	},
	["TRAIT-P-090"] = {
		kind = "perk",
		pairId = "TRAIT-090",
		name = "Ice Attunement",
		tier = "common",
		effect = "Deals 20% more damage when attacking with Ice-tagged attacks.",
		category = "Element",
	},
	["TRAIT-P-091"] = {
		kind = "perk",
		pairId = "TRAIT-091",
		name = "Iron Stomach (Greater)",
		tier = "common",
		effect = "Poison damage received -60%.",
		category = "Endurance",
	},
	["TRAIT-P-092"] = {
		kind = "perk",
		pairId = "TRAIT-092",
		name = "Ironhide (Greater)",
		tier = "uncommon",
		effect = "25% of total non-weapon WT is added as base armor",
		category = "Endurance",
	},
	["TRAIT-P-093"] = {
		kind = "perk",
		pairId = "TRAIT-093",
		name = "Item Specialist (Greater)",
		tier = "uncommon",
		effect = "Healing and Damaging items effect are increased by 30%",
		category = "General",
	},
	["TRAIT-P-094"] = {
		kind = "perk",
		pairId = "TRAIT-094",
		name = "Keen Aim (Greater)",
		tier = "uncommon",
		effect = "Precision +15%",
		category = "General",
	},
	["TRAIT-P-095"] = {
		kind = "perk",
		pairId = "TRAIT-095",
		name = "Light Step",
		tier = "uncommon",
		effect = "evasiveness + 10%",
		category = "General",
	},
	["TRAIT-P-096"] = {
		kind = "perk",
		pairId = "TRAIT-096",
		name = "Long Reach",
		tier = "common",
		effect = "+1 interact range",
		category = "Utility",
	},
	["TRAIT-P-097"] = {
		kind = "perk",
		pairId = "TRAIT-097",
		name = "Long Strider",
		tier = "common",
		effect = "+1 movement range.",
		category = "General",
	},
	["TRAIT-P-098"] = {
		kind = "perk",
		pairId = "TRAIT-098",
		name = "Longbow Specialist",
		tier = "common",
		effect = "When wielding a Longbow: weapon base damage +25% and weapon WT -25%.",
		category = "Weapon Mastery",
	},
	["TRAIT-P-099"] = {
		kind = "perk",
		pairId = "TRAIT-099",
		name = "Lucky (Greater)",
		tier = "uncommon",
		effect = "15% fortune bonus",
		category = "General",
	},
	["TRAIT-P-100"] = {
		kind = "perk",
		pairId = "TRAIT-100",
		name = "Lucky Star",
		tier = "uncommon",
		effect = "LUK +10%, VIT +10%",
		category = "General",
	},
	["TRAIT-P-101"] = {
		kind = "perk",
		pairId = "TRAIT-101",
		name = "Minion Specialist",
		tier = "uncommon",
		effect = "Summoned units has 10% more primary stats and deal 10% more damage.",
		category = "General",
	},
	["TRAIT-P-102"] = {
		kind = "perk",
		pairId = "TRAIT-102",
		name = "Nimble (Greater)",
		tier = "uncommon",
		effect = "AGI +18%",
		category = "General",
	},
	["TRAIT-P-103"] = {
		kind = "perk",
		pairId = "TRAIT-103",
		name = "Opportunist (Greater)",
		tier = "uncommon",
		effect = "Damage inflicted to targets suffering from debuff increased by 12%",
		category = "General",
	},
	["TRAIT-P-104"] = {
		kind = "perk",
		pairId = "TRAIT-104",
		name = "Pistol Specialist",
		tier = "common",
		effect = "When wielding a Pistol: weapon base damage +25% and weapon WT -25%.",
		category = "Weapon Mastery",
	},
	["TRAIT-P-105"] = {
		kind = "perk",
		pairId = "TRAIT-105",
		name = "Powerful Build",
		tier = "common",
		effect = "+1 force",
		category = "Physical Prowess",
	},
	["TRAIT-P-106"] = {
		kind = "perk",
		pairId = "TRAIT-106",
		name = "Pride",
		tier = "uncommon",
		effect = "Damage inflicted to higher level targets +10%",
		category = "General",
	},
	["TRAIT-P-107"] = {
		kind = "perk",
		pairId = "TRAIT-107",
		name = "Purifier",
		tier = "uncommon",
		effect = "Attacks dispel one random buff from target/s",
		category = "General",
	},
	["TRAIT-P-108"] = {
		kind = "perk",
		pairId = "TRAIT-108",
		name = "Quick Clotting (Greater)",
		tier = "common",
		effect = "Bleed damage received -60%.",
		category = "Endurance",
	},
	["TRAIT-P-109"] = {
		kind = "perk",
		pairId = "TRAIT-109",
		name = "Resilient (Greater)",
		tier = "uncommon",
		effect = "Recovers with 25% HP after battle or +20% of max hp when being revived.",
		category = "General",
	},
	["TRAIT-P-110"] = {
		kind = "perk",
		pairId = "TRAIT-110",
		name = "Rooted",
		tier = "common",
		effect = "+1 stability",
		category = "Endurance",
	},
	["TRAIT-P-111"] = {
		kind = "perk",
		pairId = "TRAIT-111",
		name = "Slayer",
		tier = "uncommon",
		effect = "Damage increased by 5% for each enemy unit has killed in current battle",
		category = "General",
	},
	["TRAIT-P-112"] = {
		kind = "perk",
		pairId = "TRAIT-112",
		name = "Sniper's Perch (Greater)",
		tier = "uncommon",
		effect = "+2 range if unit did not move in previous turn.",
		category = "Tactical",
	},
	["TRAIT-P-113"] = {
		kind = "perk",
		pairId = "TRAIT-113",
		name = "Spear Specialist",
		tier = "common",
		effect = "When wielding a Spear: weapon base damage +25% and weapon WT -25%.",
		category = "Weapon Mastery",
	},
	["TRAIT-P-114"] = {
		kind = "perk",
		pairId = "TRAIT-114",
		name = "Stable Land",
		tier = "uncommon",
		effect = "Tile under unit will not be inflicted effects while unit is occupying tile. This does not remove existing tile effects if unit moves to a tile with effects",
		category = "General",
	},
	["TRAIT-P-115"] = {
		kind = "perk",
		pairId = "TRAIT-115",
		name = "Staff Specialist",
		tier = "common",
		effect = "When wielding a Staff: weapon base damage +25% and weapon WT -25%.",
		category = "Weapon Mastery",
	},
	["TRAIT-P-116"] = {
		kind = "perk",
		pairId = "TRAIT-116",
		name = "Stalwart",
		tier = "uncommon",
		effect = "VIT +10%, STR +10%",
		category = "General",
	},
	["TRAIT-P-117"] = {
		kind = "perk",
		pairId = "TRAIT-117",
		name = "Steady Aim",
		tier = "uncommon",
		effect = "Ranged attacks: Hit Quality +0.05",
		category = "General",
	},
	["TRAIT-P-118"] = {
		kind = "perk",
		pairId = "TRAIT-118",
		name = "Strong Back (Greater)",
		tier = "uncommon",
		effect = "Gear WT reduced by 25% added to STR bonus",
		category = "General",
	},
	["TRAIT-P-119"] = {
		kind = "perk",
		pairId = "TRAIT-119",
		name = "Sword Breaker Specialist",
		tier = "common",
		effect = "When wielding a Sword Breaker: weapon base damage +25% and weapon WT -25%.",
		category = "Weapon Mastery",
	},
	["TRAIT-P-120"] = {
		kind = "perk",
		pairId = "TRAIT-120",
		name = "Sword Specialist",
		tier = "common",
		effect = "When wielding a Sword: weapon base damage +25% and weapon WT -25%.",
		category = "Weapon Mastery",
	},
	["TRAIT-P-121"] = {
		kind = "perk",
		pairId = "TRAIT-121",
		name = "Tough Skin (Greater)",
		tier = "uncommon",
		effect = "Takes 15% less damage.",
		category = "General",
	},
	["TRAIT-P-122"] = {
		kind = "perk",
		pairId = "TRAIT-122",
		name = "Treasure Seeker",
		tier = "uncommon",
		effect = "Opening Treasures Cost no AP. Gain 50% more reward from treasures chests unit opened.",
		category = "General",
	},
	["TRAIT-P-123"] = {
		kind = "perk",
		pairId = "TRAIT-123",
		name = "Wand Specialist",
		tier = "common",
		effect = "When wielding a Wand: weapon base damage +25% and weapon WT -25%.",
		category = "Weapon Mastery",
	},
	["TRAIT-P-124"] = {
		kind = "perk",
		pairId = "TRAIT-124",
		name = "War Axe Specialist",
		tier = "common",
		effect = "When wielding a War Axe: weapon base damage +25% and weapon WT -25%.",
		category = "Weapon Mastery",
	},
	["TRAIT-P-125"] = {
		kind = "perk",
		pairId = "TRAIT-125",
		name = "Water Attunement",
		tier = "uncommon",
		effect = "Deals 20% more damage when attacking with Water-tagged attacks.",
		category = "Element",
	},
	["TRAIT-P-126"] = {
		kind = "perk",
		pairId = "TRAIT-126",
		name = "Whip Specialist",
		tier = "common",
		effect = "When wielding a Whip: weapon base damage +25% and weapon WT -25%.",
		category = "Weapon Mastery",
	},
	["TRAIT-P-127"] = {
		kind = "perk",
		pairId = "TRAIT-127",
		name = "Wiry",
		tier = "uncommon",
		effect = "STR +10%, AGI +10%",
		category = "General",
	},
	["TRAIT-P-128"] = {
		kind = "perk",
		pairId = "TRAIT-128",
		name = "Adept",
		tier = "rare",
		effect = "Skill damage +15%",
		category = "General",
	},
	["TRAIT-P-129"] = {
		kind = "perk",
		pairId = "TRAIT-129",
		name = "Air Guard",
		tier = "rare",
		effect = "Damage received enemies equiped with ranged weapons reduced by 25%",
		category = "General",
	},
	["TRAIT-P-130"] = {
		kind = "perk",
		pairId = "TRAIT-130",
		name = "Ambusher (Greater)",
		tier = "rare",
		effect = "when attack target is at higher elevation, +11% damage per elevation difference",
		category = "General",
	},
	["TRAIT-P-131"] = {
		kind = "perk",
		pairId = "TRAIT-131",
		name = "Bloodbath",
		tier = "rare",
		effect = "Recover 15% of max HP upon KO of enemy. If multiple enemies, cap at 45% HP.",
		category = "General",
	},
	["TRAIT-P-132"] = {
		kind = "perk",
		pairId = "TRAIT-132",
		name = "Cleanse",
		tier = "rare",
		effect = "Killing enemy removes 1 random debuff",
		category = "General",
	},
	["TRAIT-P-133"] = {
		kind = "perk",
		pairId = "TRAIT-133",
		name = "Diffuser",
		tier = "rare",
		effect = "received half damage from AOE attacks",
		category = "Endurance",
	},
	["TRAIT-P-134"] = {
		kind = "perk",
		pairId = "TRAIT-134",
		name = "Dodger",
		tier = "rare",
		effect = "Until next Turn, gain +5% evasion per tile traveled (using skill or by move)",
		category = "General",
	},
	["TRAIT-P-135"] = {
		kind = "perk",
		pairId = "TRAIT-135",
		name = "Far-Sighted (Greater)",
		tier = "rare",
		effect = "Discovery radius +1.2",
		category = "General",
	},
	["TRAIT-P-136"] = {
		kind = "perk",
		pairId = "TRAIT-136",
		name = "High Ground (Greater)",
		tier = "rare",
		effect = "when attack target is at lower elevation, +7% damage per elevation difference",
		category = "Tactical",
	},
	["TRAIT-P-137"] = {
		kind = "perk",
		pairId = "TRAIT-137",
		name = "Light Step (Greater)",
		tier = "rare",
		effect = "evasiveness + 12%",
		category = "General",
	},
	["TRAIT-P-138"] = {
		kind = "perk",
		pairId = "TRAIT-138",
		name = "Long Reach (Greater)",
		tier = "rare",
		effect = "+2 interact range",
		category = "Utility",
	},
	["TRAIT-P-139"] = {
		kind = "perk",
		pairId = "TRAIT-139",
		name = "Long Strider (Greater)",
		tier = "rare",
		effect = "+2 movement range.",
		category = "General",
	},
	["TRAIT-P-140"] = {
		kind = "perk",
		pairId = "TRAIT-140",
		name = "Melee Specialist",
		tier = "rare",
		effect = "Damage inflicted with melee weapon increased by 15%, damage received from melee weapon reduced by 15%",
		category = "General",
	},
	["TRAIT-P-141"] = {
		kind = "perk",
		pairId = "TRAIT-141",
		name = "Minion Specialist (Greater)",
		tier = "rare",
		effect = "Summoned units has 12% more primary stats and deal 10% more damage.",
		category = "General",
	},
	["TRAIT-P-142"] = {
		kind = "perk",
		pairId = "TRAIT-142",
		name = "Pathfinder",
		tier = "rare",
		effect = "ignore + movement costs from terrain",
		category = "Utility",
	},
	["TRAIT-P-143"] = {
		kind = "perk",
		pairId = "TRAIT-143",
		name = "Powerful Build (Greater)",
		tier = "rare",
		effect = "+2 force",
		category = "Physical Prowess",
	},
	["TRAIT-P-144"] = {
		kind = "perk",
		pairId = "TRAIT-144",
		name = "Pride (Greater)",
		tier = "rare",
		effect = "Damage inflicted to higher level targets +12%",
		category = "General",
	},
	["TRAIT-P-145"] = {
		kind = "perk",
		pairId = "TRAIT-145",
		name = "Retaliator",
		tier = "rare",
		effect = "inflict debuff to attacker (rolled per unit)",
		category = "Combat",
	},
	["TRAIT-P-146"] = {
		kind = "perk",
		pairId = "TRAIT-146",
		name = "Rooted (Greater)",
		tier = "rare",
		effect = "+2 stability",
		category = "Endurance",
	},
	["TRAIT-P-147"] = {
		kind = "perk",
		pairId = "TRAIT-147",
		name = "Slayer (Greater)",
		tier = "rare",
		effect = "Damage increased by 6% for each enemy unit has killed in current battle",
		category = "General",
	},
	["TRAIT-P-148"] = {
		kind = "perk",
		pairId = "TRAIT-148",
		name = "Soul Charge",
		tier = "rare",
		effect = "Recover 15% of max MP upon KO of enemy. If multiple enemies, cap at 45% MP.",
		category = "General",
	},
	["TRAIT-P-149"] = {
		kind = "perk",
		pairId = "TRAIT-149",
		name = "Time Locker",
		tier = "rare",
		effect = "RT Delay caused increased by 25%",
		category = "General",
	},
	["TRAIT-P-150"] = {
		kind = "perk",
		pairId = "TRAIT-150",
		name = "Toxin Filter",
		tier = "rare",
		effect = "DOT damage reduced by half",
		category = "Endurance",
	},
	["TRAIT-P-151"] = {
		kind = "perk",
		pairId = "TRAIT-151",
		name = "Treasure Seeker (Greater)",
		tier = "rare",
		effect = "Opening Treasures Cost no AP. Gain 60% more reward from treasures chests unit opened.",
		category = "General",
	},
	["TRAIT-P-152"] = {
		kind = "perk",
		pairId = "TRAIT-152",
		name = "Wrathful",
		tier = "rare",
		effect = "Every time unit is attacked, gain a 10% damage bonus. Accumulates. Remove at end of next turn.",
		category = "General",
	},
	["TRAIT-P-153"] = {
		kind = "perk",
		pairId = "TRAIT-153",
		name = "Adept (Greater)",
		tier = "epic",
		effect = "Skill damage +18%",
		category = "General",
	},
	["TRAIT-P-154"] = {
		kind = "perk",
		pairId = "TRAIT-154",
		name = "Berserker Blood",
		tier = "epic",
		effect = "While below 30% HP: Final damage dealt +20%",
		category = "General",
	},
	["TRAIT-P-155"] = {
		kind = "perk",
		pairId = "TRAIT-155",
		name = "Bleed Specialist",
		tier = "epic",
		effect = "Attacking a target with bleed triggers bleed damage. Attacking a unit without bleed inflicts bleed.",
		category = "General",
	},
	["TRAIT-P-156"] = {
		kind = "perk",
		pairId = "TRAIT-156",
		name = "Bloodbath (Greater)",
		tier = "epic",
		effect = "Recover 18% of max HP upon KO of enemy. If multiple enemies, cap at 45% HP.",
		category = "General",
	},
	["TRAIT-P-157"] = {
		kind = "perk",
		pairId = "TRAIT-157",
		name = "Burn Specialist",
		tier = "epic",
		effect = "Attacking a target with burn triggers accumulated burn damage. Burn inflicted +5% of base damage.",
		category = "General",
	},
	["TRAIT-P-158"] = {
		kind = "perk",
		pairId = "TRAIT-158",
		name = "Determined",
		tier = "epic",
		effect = "While below 30% HP: Defense +30%",
		category = "General",
	},
	["TRAIT-P-159"] = {
		kind = "perk",
		pairId = "TRAIT-159",
		name = "Guard Specialist",
		tier = "epic",
		effect = "Damage Reduction from guard +10%",
		category = "General",
	},
	["TRAIT-P-160"] = {
		kind = "perk",
		pairId = "TRAIT-160",
		name = "Lifesteal",
		tier = "epic",
		effect = "Heal 8% of direct damage dealt",
		category = "General",
	},
	["TRAIT-P-161"] = {
		kind = "perk",
		pairId = "TRAIT-161",
		name = "Melee Specialist (Greater)",
		tier = "epic",
		effect = "Damage inflicted with melee weapon increased by 18%, damage received from melee weapon reduced by 15%",
		category = "General",
	},
	["TRAIT-P-162"] = {
		kind = "perk",
		pairId = "TRAIT-162",
		name = "Momentum",
		tier = "epic",
		effect = "once per turn, gain 1AP upon KO of enemy",
		category = "General",
	},
	["TRAIT-P-163"] = {
		kind = "perk",
		pairId = "TRAIT-163",
		name = "Poison Specialist",
		tier = "epic",
		effect = "Attacking a target with poison triggers poison damage. Attacking a unit without poison inflicts poison.",
		category = "General",
	},
	["TRAIT-P-164"] = {
		kind = "perk",
		pairId = "TRAIT-164",
		name = "Quick",
		tier = "epic",
		effect = "10% lower base RT",
		category = "General",
	},
	["TRAIT-P-165"] = {
		kind = "perk",
		pairId = "TRAIT-165",
		name = "Soul Charge (Greater)",
		tier = "epic",
		effect = "Recover 18% of max MP upon KO of enemy. If multiple enemies, cap at 45% MP.",
		category = "General",
	},
	["TRAIT-P-166"] = {
		kind = "perk",
		pairId = "TRAIT-166",
		name = "Venom Specialist",
		tier = "epic",
		effect = "Attacking a target with venom triggers venom damage. Attacking a unit without venom inflicts venom.",
		category = "General",
	},
	["TRAIT-P-167"] = {
		kind = "perk",
		pairId = "TRAIT-167",
		name = "Wrathful (Greater)",
		tier = "epic",
		effect = "Every time unit is attacked, gain a 12% damage bonus. Accumulates. Remove at end of next turn.",
		category = "General",
	},
	["TRAIT-P-168"] = {
		kind = "perk",
		pairId = "TRAIT-168",
		name = "Arcane Prodigy",
		tier = "legendary",
		effect = "Skill Potency +12%, Skill RT Cost -8%",
		category = "General",
	},
	["TRAIT-P-169"] = {
		kind = "perk",
		pairId = "TRAIT-169",
		name = "Berserker Blood (Greater)",
		tier = "legendary",
		effect = "While below 36% HP: Final damage dealt +20%",
		category = "General",
	},
	["TRAIT-P-170"] = {
		kind = "perk",
		pairId = "TRAIT-170",
		name = "Determined (Greater)",
		tier = "legendary",
		effect = "While below 36% HP: Defense +30%",
		category = "General",
	},
	["TRAIT-P-171"] = {
		kind = "perk",
		pairId = "TRAIT-171",
		name = "Dual Strike",
		tier = "legendary",
		effect = "Basic Attack resolves twice (both hits apply full effects). Double RT cost",
		category = "General",
	},
	["TRAIT-P-172"] = {
		kind = "perk",
		pairId = "TRAIT-172",
		name = "Elemental Mastery",
		tier = "legendary",
		effect = "All elemental damage dealt +18%, elemental damage received -8%",
		category = "General",
	},
	["TRAIT-P-173"] = {
		kind = "perk",
		pairId = "TRAIT-173",
		name = "Guard Specialist (Greater)",
		tier = "legendary",
		effect = "Damage Reduction from guard +12%",
		category = "General",
	},
	["TRAIT-P-174"] = {
		kind = "perk",
		pairId = "TRAIT-174",
		name = "Lifesteal (Greater)",
		tier = "legendary",
		effect = "Heal 9.6% of direct damage dealt",
		category = "General",
	},
	["TRAIT-P-175"] = {
		kind = "perk",
		pairId = "TRAIT-175",
		name = "Martial Footwork",
		tier = "legendary",
		effect = "If first action each turn is Move, replenish 1 AP after move",
		category = "General",
	},
	["TRAIT-P-176"] = {
		kind = "perk",
		pairId = "TRAIT-176",
		name = "Overwhelming Force",
		tier = "legendary",
		effect = "Force +2; all melee Basic Attacks gain Knockback",
		category = "General",
	},
	["TRAIT-P-177"] = {
		kind = "perk",
		pairId = "TRAIT-177",
		name = "Soul Harvest",
		tier = "legendary",
		effect = "On KO enemy: heal 12% Max HP and recover 8% Max MP",
		category = "General",
	},
	["TRAIT-P-178"] = {
		kind = "perk",
		pairId = "TRAIT-178",
		name = "Timeline Sovereign",
		tier = "legendary",
		effect = "Base RT -10%, Starting RT -12%, RT delay inflicted +10%",
		category = "General",
	},
	["TRAIT-P-179"] = {
		kind = "perk",
		pairId = "TRAIT-179",
		name = "Undying Will",
		tier = "legendary",
		effect = "On first KO: revive with 25% HP after 500 CT (once per battle)",
		category = "General",
	},
}

-- Tier roll chances (percent) — from unit_trait_roll_chances
TraitData.TierChances = {
	{tier = "common", pct = 40},
	{tier = "uncommon", pct = 28},
	{tier = "rare", pct = 18},
	{tier = "epic", pct = 10},
	{tier = "legendary", pct = 4},
}

-- Pre-grouped pools (built once at load): tier -> {perkIds}, tier -> {flawIds}
TraitData.PerkPools = {}
TraitData.FlawPools = {}
do
	for id, t in pairs(TraitData.Traits) do
		local pool = (t.kind == "perk") and TraitData.PerkPools or TraitData.FlawPools
		pool[t.tier] = pool[t.tier] or {}
		table.insert(pool[t.tier], id)
	end
	-- sort each pool for deterministic indexing
	for _, pools in ipairs({TraitData.PerkPools, TraitData.FlawPools}) do
		for _, ids in pairs(pools) do table.sort(ids) end
	end
end

-- Lookup a trait by its trait_id (returns the trait table or nil)
function TraitData.GetTrait(traitId)
	if not traitId then return nil end
	return TraitData.Traits[traitId]
end

function TraitData.GetAllPerkIds()
	local ids = {}
	for id, t in pairs(TraitData.Traits) do
		if t.kind == "perk" then table.insert(ids, id) end
	end
	table.sort(ids)
	return ids
end

function TraitData.GetAllFlawIds()
	local ids = {}
	for id, t in pairs(TraitData.Traits) do
		if t.kind == "flaw" then table.insert(ids, id) end
	end
	table.sort(ids)
	return ids
end

-- Get the perk/flaw pool for a given tier (kind = "perk" or "flaw")
function TraitData.GetPool(kind, tier)
	local pools = (kind == "perk") and TraitData.PerkPools or TraitData.FlawPools
	return pools[tier] or {}
end

return TraitData
